# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class Vakint:
    ...

class VakintEvaluationMethod:
    ...

class VakintExpression:
    ...

class VakintNumericalResult:
    ...

