"""Public symbol accessors must agree with the expressions generated by models."""

import ast
import json
import re
from pathlib import Path

import pytest
from symbolica import S
from symbolica.community import hep, tensor


def test_model_references_work_with_native_coupling_expansion():
    model = hep.Model.standard_model()
    for coupling in model.couplings:
        assert model.expand_couplings(coupling.symbol) == coupling.expression
    for parameter in model.parameters:
        assert parameter.symbol.get_name().split("::")[-1] == parameter.name
    assert model.particle("e-").mass == model.parameter("Me").symbol
    assert model.particle("a").mass == 0
    assert model.parameter("MW").symbol != model.parameter("MW").expression
    definition = json.loads(model.to_json())
    definition["functions"] = [
        {"name": "square", "arguments": ["x"], "expression": "x^2"}
    ]
    custom = hep.Model.from_json(json.dumps(definition))
    assert custom.function("square").symbol.get_name().endswith("::square")


def test_public_heads_match_typed_tensors_and_generated_momenta():
    metric = tensor.TensorName.g()
    gamma = tensor.TensorName.dirac_gamma()
    lorentz = tensor.Representation.mink(4)
    assert (
        tensor.TensorExpression.g(lorentz).structure.name.to_expression()
        == metric.to_expression()
    )
    assert (
        tensor.TensorExpression.dirac_gamma(4).structure.name.to_expression()
        == gamma.to_expression()
    )
    amplitude = (
        hep.Model.phi4()
        .process(["phi", "phi"], ["phi", "phi"])
        .generate_amplitude(max_vertices=1)
    )
    for leg in amplitude.legs:
        assert leg.momentum == hep.Kinematics.external_momentum(leg.index)
    # A user-defined symbol with the same short name cannot capture the accessor.
    assert S("user_notebook::P") != hep.Kinematics.external_momentum


def test_particle_mass_and_signed_electric_charge():
    model = hep.Model.qed()
    electron = model.particle("e-")
    mass, charge = electron.mass, electron.electric_charge
    e = model.parameter("ee").symbol
    assert mass == model.parameter("Me").symbol
    assert charge == -e
    assert electron.charge == -1
    assert electron.antiparticle.electric_charge == e
    assert model.particle("u").electric_charge == 2 * e / 3
    assert model.particle("b").electric_charge == -e / 3
    assert model.particle("a").electric_charge == 0
    assert model.particle("a").mass == 0
    assert "m_e" in mass.to_latex()
    for particle in model.particles:
        assert particle.electric_charge == particle.charge * e
        assert particle.antiparticle.electric_charge == -particle.electric_charge

    scalar = hep.Model.scalar_qed()
    scalar_e = scalar.parameter("e").symbol
    assert scalar.particle("phi+").electric_charge == scalar_e
    assert scalar.particle("phi-").electric_charge == -scalar_e
    assert scalar_e == scalar.parameter("e").symbol
    assert r"\lambda" not in scalar_e.to_latex()
    neutral = hep.Model.phi4()
    assert neutral.particle("phi").electric_charge == 0
    assert not hasattr(model, "electromagnetic_coupling")
    assert not hasattr(neutral, "electromagnetic_coupling")


def test_electric_charge_uses_vertex_expressions_and_normalization():
    model = hep.Model.qed()
    # Renaming parameters, vertices, couplings and Lorentz structures must not
    # affect the physical charge. No model-schema addition identifies e.
    source = model.to_json()
    for old, new in [
        ("ee", "customElectricCoupling"),
        ("GC_3", "customCoupling"),
        ("FFV1", "customLorentz"),
        ("V_98", "customVertex"),
    ]:
        source = re.sub(r"\b" + old + r"\b", new, source)
    definition = json.loads(source)
    assert "electromagnetic_coupling" not in definition
    # Move a factor from the coupling to the Lorentz structure. Reading only
    # the coupling coefficient would incorrectly return one third of the charge.
    affected = set()
    for vertex in definition["vertex_rules"]:
        if "customLorentz" in vertex["lorentz_structures"]:
            column = vertex["lorentz_structures"].index("customLorentz")
            affected.update(row[column] for row in vertex["couplings"])
    for lorentz in definition["lorentz_structures"]:
        if lorentz["name"] == "customLorentz":
            lorentz["structure"] = "3*(" + lorentz["structure"] + ")"
    for coupling in definition["couplings"]:
        if coupling["name"] in affected:
            coupling["expression"] = "(" + coupling["expression"] + ")/3"
    custom = hep.Model.from_json(json.dumps(definition))
    expected = custom.parameter("customElectricCoupling").symbol
    assert custom.particle("e-").electric_charge == -expected
    assert custom.particle("u").electric_charge == 2 * expected / 3
    restored = hep.Model.from_json(custom.to_json())
    assert restored.particle("e+").electric_charge == expected

    definition["vertex_rules"] = []
    disconnected = hep.Model.from_json(json.dumps(definition))
    assert disconnected.particle("a").electric_charge == 0
    with pytest.raises(hep.ModelError, match="no supported minimal photon"):
        _ = disconnected.particle("e-").electric_charge

    inconsistent = json.loads(model.to_json())
    up_vertex = next(
        v
        for v in inconsistent["vertex_rules"]
        if sorted(v["particles"]) == ["a", "u", "u~"]
    )
    up_coupling = up_vertex["couplings"][0][0]
    for coupling in inconsistent["couplings"]:
        if coupling["name"] == up_coupling:
            coupling["expression"] = "2*(" + coupling["expression"] + ")"
    inconsistent = hep.Model.from_json(json.dumps(inconsistent))
    with pytest.raises(hep.ModelError, match="inconsistent electric charge"):
        _ = inconsistent.particle("e-").electric_charge


def test_notebook_sources_do_not_fetch_internal_namespace_symbols():
    examples = Path(__file__).parents[1] / "examples"
    for path in examples.rglob("*"):
        if path.suffix == ".ipynb":
            sources = [
                "".join(cell["source"])
                for cell in json.loads(path.read_text())["cells"]
                if cell["cell_type"] == "code"
            ]
        elif path.suffix == ".py" and "@app.cell" in path.read_text():
            sources = [path.read_text()]
        else:
            continue
        for source in sources:
            # Inspect calls rather than saved output or explanatory prose.
            for node in ast.walk(ast.parse(source)):
                if not isinstance(node, ast.Call):
                    continue
                name = getattr(node.func, "id", getattr(node.func, "attr", ""))
                if name not in {"S", "E", "TensorName", "parse"}:
                    continue
                for argument in node.args:
                    if isinstance(argument, ast.Constant) and isinstance(
                        argument.value, str
                    ):
                        assert not any(
                            prefix in argument.value
                            for prefix in ("UFO::", "gammalooprs::", "spenso::")
                        ), (path, node.lineno, argument.value)
