# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import decimal
import os
import pathlib
import typing
from symbolica.community.hepkit import FeynmanDiagram, IntegralFamily, Kinematics, Model
from symbolica.core import ComplexFloat, Expression, Float

class AccuracyError(NumericalError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class AmplitudeResult:
    r"""
    Physical observables with conditional propagated uncertainties and arithmetic refinement.
    """
    @property
    def values(self) -> builtins.dict[builtins.str, Float]: ...
    @property
    def absolute_errors(self) -> builtins.dict[builtins.str, Float]: ...
    @property
    def verified_relative_digits(self) -> builtins.dict[builtins.str, typing.Optional[builtins.int]]: ...
    @property
    def arithmetic_changes(self) -> builtins.dict[builtins.str, Float]: ...
    @property
    def working_bits(self) -> builtins.int: ...
    @property
    def provenance(self) -> builtins.str: ...
    @property
    def elapsed_nanoseconds(self) -> builtins.int: ...

@typing.final
class AsymptoticCoefficient:
    r"""
    Select a power/log coefficient in a declared endpoint chart.
    For epsilon hierarchies, component is epsilon_offset * basis_size + component.
    """
    @property
    def component(self) -> builtins.int: ...
    @property
    def power(self) -> Expression: ...
    @property
    def log_power(self) -> builtins.int: ...
    def __new__(cls, component: builtins.int, power: Expression, log_power: builtins.int = 0) -> AsymptoticCoefficient: ...

@typing.final
class AsymptoticRelation:
    r"""
    Assert sum(weight * selected coefficient) = value using exact expressions.
    This is supplied physical information, never inferred from numerical errors.
    """
    @property
    def terms(self) -> builtins.list[tuple[AsymptoticCoefficient, Expression]]: ...
    @property
    def value(self) -> Expression: ...
    def __new__(cls, terms: typing.Sequence[tuple[AsymptoticCoefficient, Expression]], value: Expression) -> AsymptoticRelation: ...

@typing.final
class BoundaryCache:
    r"""
    Shared, progressively filled cache of verified physical boundary values.
    """
    def __new__(cls) -> BoundaryCache: ...
    @staticmethod
    def load(directory: builtins.str | os.PathLike | pathlib.Path) -> BoundaryCache: ...
    def save(self, directory: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Atomically persist versioned native binary entries and their provenance.
        """
    def extend(self, other: BoundaryCache) -> None:
        r"""
        Merge compatible entries while retaining intermediate points and stronger evidence.
        Repeated merges and merging a cache with itself are safe and idempotent.
        """
    def __len__(self) -> builtins.int:
        r"""
        Number of regular initial conditions; endpoint_entries() is separate.
        """
    def entries(self) -> builtins.list[TransportResult]:
        r"""
        Inspect retained points without exposing mutable cache entries.
        """
    def endpoint_entries(self) -> builtins.list[EndpointResult]:
        r"""
        Terminal endpoint records are separate from regular initial conditions.
        """

class BoundaryCacheError(EvaluationError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class BoundaryData:
    r"""
    Supplied regular-point initial values. Accuracy is an explicit caller claim.
    """
    @property
    def point(self) -> ComplexFloat: ...
    @property
    def values(self) -> builtins.list[ComplexFloat]: ...
    @property
    def verified_digits(self) -> typing.Optional[builtins.int]: ...
    @property
    def provenance(self) -> builtins.str: ...
    def __new__(cls, point: ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal], values: typing.Sequence[ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]], *, verified_digits: typing.Optional[builtins.int] = None, provenance: builtins.str = 'caller supplied') -> BoundaryData: ...

class CalculationCancelled(EvaluationError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class ComputationControl:
    r"""
    Thread-safe cancellation and progress polling for a running calculation.
    Run an evaluator in a worker thread and poll this object from the UI thread.
    At most the 4096 most recent progress events are retained.
    """
    @property
    def cancelled(self) -> builtins.bool: ...
    def __new__(cls) -> ComputationControl: ...
    def cancel(self) -> None: ...
    def poll(self) -> builtins.list[builtins.str]:
        r"""
        Drain queued progress events. Cancellation remains set for this control.
        """

@typing.final
class ContinuationPrescription:
    r"""
    Exact polynomial i0 declarations for physical threshold continuation.
    Declarations retain their order. The native connection validates their
    variables and original domains when this object is bound to a transport.
    A declaration fixes local sides; it does not establish global monodromy.
    """
    @property
    def prescriptions(self) -> builtins.list[tuple[Expression, builtins.str]]: ...
    @property
    def domain(self) -> builtins.str: ...
    @property
    def unprescribed_side(self) -> builtins.str: ...
    def __new__(cls, prescriptions: typing.Sequence[tuple[Expression, builtins.str]], *, domain: builtins.str, unprescribed_side: builtins.str = '+i0') -> ContinuationPrescription: ...

@typing.final
class DifferentialSystem:
    r"""
    Regular-point rational differential equation dY/dx = A(x)Y.
    """
    @property
    def matrix(self) -> builtins.list[builtins.list[Expression]]: ...
    @property
    def variable(self) -> Expression: ...
    def __new__(cls, variable: Expression, matrix: typing.Sequence[typing.Sequence[Expression]]) -> DifferentialSystem: ...
    def blocks(self) -> builtins.list[builtins.list[builtins.int]]: ...
    def change_basis(self, matrix: typing.Sequence[typing.Sequence[Expression]]) -> DifferentialSystem: ...
    def transport(self, boundary: BoundaryData, waypoints: typing.Sequence[ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]], *, parameters: typing.Optional[typing.Mapping[Expression, ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]]] = None, options: typing.Optional[EvaluationOptions] = None, control: typing.Optional[ComputationControl] = None) -> TransportResult:
        r"""
        Fixed-precision continuation. Returned diagnostics do not certify a global error bound.
        """

@typing.final
class EndpointConstraints:
    r"""
    Explicit exact endpoint relations, their provenance and bounded work settings.
    Weights and values are Gaussian-rational; selected powers are real rational.
    Numerical matching and uncertainty remain separate from these assumptions.
    """
    @property
    def relations(self) -> builtins.list[AsymptoticRelation]: ...
    @property
    def provenance(self) -> builtins.str: ...
    @property
    def max_dimension(self) -> builtins.int: ...
    @property
    def max_order(self) -> builtins.int: ...
    @property
    def max_coefficient_bits(self) -> builtins.int: ...
    @property
    def max_scalar_cells(self) -> builtins.int: ...
    def __new__(cls, relations: typing.Sequence[AsymptoticRelation], provenance: builtins.str, *, max_dimension: builtins.int = 64, max_order: builtins.int = 256, max_coefficient_bits: builtins.int = 65536, max_scalar_cells: builtins.int = 4000000) -> EndpointConstraints: ...

@typing.final
class EndpointResult:
    r"""
    Finite epsilon coefficient limits and estimated accuracy, with their regular anchor.
    These terminal values cannot be used as initial data for a singular ODE.
    """
    @property
    def constraints(self) -> typing.Optional[EndpointConstraints]: ...
    @property
    def route(self) -> EndpointRoute: ...
    @property
    def matching_boundary(self) -> TransportResult: ...
    @property
    def coefficients(self) -> builtins.list[builtins.list[ComplexFloat]]:
        r"""
        Rows are epsilon powers, columns are the original physical basis.
        """
    @property
    def comparison_errors(self) -> builtins.list[builtins.list[Float]]: ...
    @property
    def leading_power(self) -> builtins.int: ...
    @property
    def last_power(self) -> builtins.int: ...
    @property
    def verified_digits(self) -> builtins.int: ...
    @property
    def input_verified_digits(self) -> builtins.int: ...
    @property
    def working_bits(self) -> builtins.int: ...
    @property
    def provenance(self) -> builtins.str: ...
    @property
    def cache_hit(self) -> builtins.bool: ...
    @property
    def elapsed_nanoseconds(self) -> builtins.int: ...

@typing.final
class EndpointRoute:
    r"""
    Exact endpoint chart, with endpoint at parameter zero and a regular matching point.
    Root signs and log winding describe the caller's explicitly admitted approach.
    """
    @property
    def parameter(self) -> Expression: ...
    @property
    def coordinates(self) -> builtins.dict[Expression, Expression]: ...
    @property
    def matching_parameter(self) -> Expression: ...
    @property
    def matching_coordinates(self) -> builtins.dict[Expression, Expression]: ...
    @property
    def root_sheets(self) -> builtins.dict[Expression, builtins.int]: ...
    @property
    def winding(self) -> builtins.int: ...
    @property
    def homotopy(self) -> builtins.str: ...
    def __new__(cls, parameter: Expression, coordinates: typing.Mapping[Expression, Expression], matching_parameter: Expression, *, homotopy: builtins.str, root_sheets: typing.Optional[typing.Mapping[Expression, builtins.int]] = None, winding: builtins.int = 0) -> EndpointRoute: ...

class EvaluationError(builtins.Exception):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class EvaluationOptions:
    r"""
    Requested accuracy and resource limits. Working precision is not achieved accuracy.
    """
    @property
    def digits(self) -> builtins.int: ...
    @property
    def guard_digits(self) -> builtins.int: ...
    @property
    def series_order(self) -> builtins.int: ...
    @property
    def pade_degree(self) -> typing.Optional[builtins.int]:
        r"""
        Optional rational approximation degree; absent means Taylor transport.
        """
    @property
    def residual_arithmetic(self) -> builtins.str:
        r"""
        Source-defect arithmetic: ball (default) or adaptive_integer (opt-in).
        """
    @property
    def boundary_error_strategy(self) -> builtins.str:
        r"""
        Supplied-error propagation policy; unavailable proofs retain scalar bounds.
        """
    @property
    def workers(self) -> builtins.int: ...
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def mass_mode(self) -> builtins.str:
        r"""
        Auxiliary mass placement name; explicit selections retain their slot list.
        """
    @property
    def deformed_propagator_slots(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Zero-based physical denominator slots, never HEPKit edge IDs or ISP slots.
        """
    def __new__(cls, *, digits: builtins.int = 20, guard_digits: builtins.int = 40, series_order: builtins.int = 80, max_steps: builtins.int = 1000, workers: builtins.int = 1, dimension: builtins.int = 4, recursion: builtins.str = 'auxiliary_mass', prescription: builtins.str = '+i0', mass_mode: typing.Optional[builtins.str] = None, deformed_propagator_slots: typing.Optional[typing.Sequence[builtins.int]] = None, refine_basis: builtins.bool = False, skip_reduction: builtins.bool = False, sampled_reduction: builtins.bool = True, max_precision_attempts: builtins.int = 3, max_boundary_attempts: builtins.int = 8, cache_directory: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, local_coordinate: builtins.str = 'identity', sample_cache_directory: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, reuse_samples: builtins.bool = True, pade_degree: typing.Optional[builtins.int] = None, residual_arithmetic: builtins.str = 'ball', boundary_error_strategy: builtins.str = 'automatic') -> EvaluationOptions: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class FormFactorResult:
    r"""
    Four normalized form factors, with propagated master-integral uncertainties.
    """
    @property
    def values(self) -> builtins.list[ComplexFloat]: ...
    @property
    def absolute_errors(self) -> builtins.list[Float]: ...
    @property
    def verified_relative_digits(self) -> builtins.list[typing.Optional[builtins.int]]: ...
    @property
    def provenance(self) -> builtins.str: ...

@typing.final
class HiggsJetAmplitude:
    r"""
    Coherent W/Z and infinite-top Higgs-plus-jet observables in the effective model's basis.
    Construction reuses the supplied model for generation, display, and contraction.
    Cancellation is checked between native stages; an active HEPKit or Idenso
    operation completes before acknowledging a cancellation request.
    """
    @property
    def diagrams(self) -> builtins.list[FeynmanDiagram]:
        r"""
        Native effective diagrams sharing the original model instance.
        """
    @property
    def expressions(self) -> builtins.list[Expression]:
        r"""
        Exact EW square, interference, and effective square kernels, in that order.
        """
    @property
    def coordinate_symbols(self) -> builtins.list[Expression]: ...
    def __new__(cls, model: Model, *, control: typing.Optional[ComputationControl] = None) -> HiggsJetAmplitude: ...
    def evaluate(self, s: Expression, t: Expression, higgs_mass_squared: Expression, w_factors: typing.Sequence[ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]], z_factors: typing.Sequence[ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]], w_errors: typing.Sequence[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal], z_errors: typing.Sequence[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal], *, parameters: typing.Mapping[Expression, Expression], provenance: builtins.str, digits: builtins.int = 20, guard_digits: builtins.int = 40, control: typing.Optional[ComputationControl] = None) -> AmplitudeResult:
        r"""
        Evaluate normalized W1..W4 and Z1..Z4 form factors and their absolute allowances.
        Model parameters are exact Symbolica expressions; model float defaults are unused.
        Coefficients must use the same physical kinematics and W/Z masses as the model inputs.
        Includes incoming spin/color averages and final-state sums, with no phase-space factor.
        """

@typing.final
class HiggsJetConfiguration:
    r"""
    Exact physical coordinates and root conventions for one mass and crossing.
    """
    @property
    def label(self) -> builtins.str: ...
    @property
    def mass(self) -> builtins.str: ...
    @property
    def permutation(self) -> builtins.int: ...
    @property
    def start(self) -> builtins.dict[Expression, Expression]: ...
    @property
    def destination(self) -> builtins.dict[Expression, Expression]: ...
    @property
    def root_sheets(self) -> builtins.dict[Expression, builtins.int]: ...

@typing.final
class HiggsJetFormFactorProjector:
    r"""
    Kinematics-dependent projection of crossed master integrals into the four
    normalized scalar Higgs-plus-jet form factors for one vector-boson mass.
    """
    def __new__(cls, *, namespace: builtins.str = 'hep_higgs_jet') -> HiggsJetFormFactorProjector: ...
    def evaluate(self, s: Expression, t: Expression, higgs_mass_squared: Expression, vector_mass_squared: Expression, planar: typing.Sequence[TransportResult], nonplanar: typing.Sequence[TransportResult], *, working_digits: builtins.int = 100) -> FormFactorResult:
        r"""
        Planar/nonplanar results are each ordered as (s,u), (s,t), (u,t), (t,s).
        """

@typing.final
class HiggsJetIntegralSystem:
    r"""
    Certified planar or nonplanar Higgs-plus-jet integral system. Generates its
    own boundary values using the supplied IntegralEvaluator's reduction backend.
    """
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def mathematical_fingerprint(self) -> builtins.str:
        r"""
        Stable mathematical certificate for portable, externally supplied seeds.
        This does not bypass runtime-sensitive binary cache compatibility checks.
        """
    @property
    def epsilon(self) -> Expression: ...
    @property
    def coordinates(self) -> builtins.list[Expression]: ...
    @property
    def roots(self) -> builtins.dict[Expression, Expression]: ...
    @property
    def physical_powers(self) -> builtins.list[builtins.list[builtins.int]]: ...
    @property
    def canonical_projection(self) -> builtins.list[builtins.list[tuple[builtins.list[builtins.int], Expression]]]: ...
    @property
    def provenance(self) -> builtins.str: ...
    def __new__(cls, topology: builtins.str, *, namespace: builtins.str = 'hep_higgs_jet') -> HiggsJetIntegralSystem: ...
    def kinematic_transport(self, options: typing.Optional[EvaluationOptions] = None) -> KinematicTransport:
        r"""
        Share this system's canonical connection and ordinary supplied-boundary
        validation. No reduction, boundary generation or numeric transport runs.
        """
    def configurations(self) -> builtins.list[HiggsJetConfiguration]: ...
    def verify_basis(self) -> None: ...
    def generate_boundary(self, evaluator: IntegralEvaluator, cache: BoundaryCache, point: typing.Mapping[Expression, Expression], root_sheets: typing.Mapping[Expression, builtins.int], *, last: builtins.int = 4, recompute: builtins.bool = False, control: typing.Optional[ComputationControl] = None) -> TransportResult:
        r"""
        Complete canonical seed generation from ordinary physical integrals.
        Recompute bypasses verified-boundary and numerical-sample reuse while
        retaining the evaluator's exact reduction cache.
        """
    def evaluate(self, cache: BoundaryCache, point: typing.Mapping[Expression, Expression], root_sheets: typing.Mapping[Expression, builtins.int], *, last: builtins.int = 4, options: typing.Optional[EvaluationOptions] = None, control: typing.Optional[ComputationControl] = None) -> TransportResult:
        r"""
        Continue within a regular real kinematic chamber, saving accepted
        intermediate physical points in the shared cache.
        """

class IncompleteReductionError(ReductionError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class IntegralEvaluator:
    r"""
    Evaluate native HEPKit families with exact reduction and recursive boundary construction.
    """
    @property
    def options(self) -> EvaluationOptions: ...
    @property
    def backend_identity(self) -> builtins.str: ...
    def evaluate_projections(self, family: IntegralFamily, projections: typing.Sequence[typing.Sequence[tuple[typing.Sequence[builtins.int], Expression]]], point: typing.Mapping[Expression, Expression], epsilon: Expression, *, last: builtins.int = 0, physical_propagators: typing.Optional[builtins.int] = None, control: typing.Optional[ComputationControl] = None) -> builtins.list[LaurentExpansion]:
        r"""
        Evaluate several exact linear combinations with shared sample values and reductions.
        Projection weights are multiplied before Laurent fitting.
        """
    def __new__(cls, *, options: typing.Optional[EvaluationOptions] = None, reductions: typing.Optional[ReductionTables] = None, reduction_depth: builtins.int = 2, reduction_targets: builtins.int = 4096, reduction_batch_size: builtins.int = 32) -> IntegralEvaluator: ...
    def evaluate(self, family: IntegralFamily, powers: typing.Sequence[typing.Sequence[builtins.int]], point: typing.Mapping[Expression, Expression], epsilon: Expression, *, last: builtins.int = 0, physical_propagators: typing.Optional[builtins.int] = None, control: typing.Optional[ComputationControl] = None) -> builtins.list[LaurentExpansion]:
        r"""
        Denominator powers follow the native family's exact input order.
        """
    def evaluate_samples(self, family: IntegralFamily, powers: typing.Sequence[typing.Sequence[builtins.int]], point: typing.Mapping[Expression, Expression], epsilon: Expression, samples: typing.Sequence[Expression], *, physical_propagators: typing.Optional[builtins.int] = None, control: typing.Optional[ComputationControl] = None) -> builtins.list[builtins.list[ComplexFloat]]:
        r"""
        Evaluate prescribed exact nonzero epsilon samples with fresh recursive boundaries.
        """
    def evaluate_diagram(self, diagram: FeynmanDiagram, kinematics: Kinematics, point: typing.Mapping[Expression, Expression], epsilon: Expression, *, last: builtins.int = 0, max_partial_fraction_states: builtins.int = 10000, control: typing.Optional[ComputationControl] = None) -> LaurentExpansion:
        r"""
        Contract the native diagram numerator, decompose it, then integrate the exact weighted sum.
        """
    def evaluate_cut_diagram(self, diagram: FeynmanDiagram, kinematics: Kinematics, point: typing.Mapping[Expression, Expression], epsilon: Expression, *, cut_index: builtins.int, future_channel: typing.Sequence[Expression], loop_prescriptions: typing.Sequence[builtins.str], edge_powers: typing.Optional[typing.Mapping[builtins.int, builtins.int]] = None, last: builtins.int = 0, control: typing.Optional[ComputationControl] = None) -> LaurentExpansion:
        r"""
        Integrate one native positive-energy cut, including the contracted numerator.
        Channel coefficients refer to the native independent external basis. Loop
        prescriptions are +i0, -i0 or insensitive in native loop-basis order.
        Raised cut powers use derivative-delta normalization; no flux or symmetry
        factor is added beyond the diagram's own exact overall factor.
        """
    def evaluate_cut_diagram_samples(self, diagram: FeynmanDiagram, kinematics: Kinematics, point: typing.Mapping[Expression, Expression], epsilon: Expression, samples: typing.Sequence[Expression], *, cut_index: builtins.int, future_channel: typing.Sequence[Expression], loop_prescriptions: typing.Sequence[builtins.str], edge_powers: typing.Optional[typing.Mapping[builtins.int, builtins.int]] = None, control: typing.Optional[ComputationControl] = None) -> builtins.list[ComplexFloat]:
        r"""
        Shared finite-epsilon cut evaluation. Exact numerator weights and cut IBP
        coefficients are applied at each nonzero sample before any truncation.
        Values have working precision; this method does not assert fitted accuracy.
        """
    def prepare(self, family: IntegralFamily, powers: typing.Sequence[typing.Sequence[builtins.int]], variables: typing.Sequence[Expression], epsilon: Expression, *, branch_domain: builtins.str, physical_propagators: typing.Optional[builtins.int] = None, fixed_parameters: typing.Optional[typing.Mapping[Expression, Expression]] = None, epsilon_shearing: builtins.bool = False, control: typing.Optional[ComputationControl] = None) -> PreparedIntegralFamily:
        r"""
        Prepare a common derivative-closed basis in all remaining physical variables.
        """

class InvalidInputError(EvaluationError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class KinematicTransport:
    r"""
    Transport a common master basis in physical invariants, reusing verified cached points.
    The declared branch domain and explicit straight-path admission are part of the
    physical continuation contract; distance alone never establishes a sheet.
    """
    @property
    def identity(self) -> builtins.str: ...
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def roots(self) -> builtins.dict[Expression, Expression]:
        r"""
        Native root declarations; discrete sheet signs live on each boundary/query.
        """
    @property
    def nonzero_conditions(self) -> builtins.list[Expression]: ...
    def evaluate_endpoint(self, cache: BoundaryCache, route: EndpointRoute, leading: builtins.int, last: builtins.int, *, admit_matching_path: builtins.bool = False, admit_endpoint: builtins.bool = False, scales: typing.Optional[typing.Mapping[Expression, Expression]] = None, max_lift_dimension: builtins.int = 256, series_order: builtins.int = 64, constraints: typing.Optional[EndpointConstraints] = None, control: typing.Optional[ComputationControl] = None) -> EndpointResult:
        r"""
        Evaluate finite epsilon coefficient limits in an exact endpoint chart.
        Admit the regular matching path and final endpoint approach separately.
        With a continuation declaration, matching uses the native prescribed
        contour and admit_matching_path admits its declared global homotopy.
        Recorded input errors and independent precision/order profiles determine
        reusable evidence; this is not symbolic dimensional-sector projection.
        """
    def __new__(cls, epsilon: Expression, derivatives: typing.Mapping[Expression, typing.Sequence[typing.Sequence[Expression]]], basis: typing.Sequence[Expression], normalization: Expression, *, branch_domain: builtins.str, roots: typing.Optional[typing.Mapping[Expression, Expression]] = None, options: typing.Optional[EvaluationOptions] = None, nonzero_conditions: typing.Optional[typing.Sequence[Expression]] = None, continuation: typing.Optional[ContinuationPrescription] = None) -> KinematicTransport:
        r"""
        Construct a general physical connection, optionally with named square roots.
        Registered roots require explicit source and destination sheet signs.
        Matrix entries may contain epsilon-independent and higher epsilon terms;
        their admission and expansion use the native connection implementation.
        """
    @staticmethod
    def canonical(epsilon: Expression, variables: typing.Sequence[Expression], letters: typing.Sequence[Expression], matrices: typing.Sequence[typing.Sequence[typing.Sequence[Expression]]], basis: typing.Sequence[Expression], normalization: Expression, *, branch_domain: builtins.str, roots: typing.Optional[typing.Mapping[Expression, Expression]] = None, options: typing.Optional[EvaluationOptions] = None, nonzero_conditions: typing.Optional[typing.Sequence[Expression]] = None, continuation: typing.Optional[ContinuationPrescription] = None) -> KinematicTransport:
        r"""
        Construct dY = epsilon sum(M_a dlog(letter_a))Y without dense physical assembly.
        Named square roots retain separate generators and explicit endpoint sheet signs.
        """
    def add_boundary(self, cache: BoundaryCache, point: typing.Mapping[Expression, Expression], coefficients: typing.Sequence[typing.Sequence[ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]]], leading: builtins.int, *, verified_digits: builtins.int, comparison_errors: typing.Sequence[typing.Sequence[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]], provenance: builtins.str, root_sheets: typing.Optional[typing.Mapping[Expression, builtins.int]] = None) -> TransportResult:
        r"""
        Insert caller-established boundary evidence. Declared accuracy is not certified here.
        Coefficients and absolute error estimates are epsilon-major arrays.
        """
    def evaluate(self, cache: BoundaryCache, destination: typing.Mapping[Expression, Expression], leading: builtins.int, last: builtins.int, *, root_sheets: typing.Optional[typing.Mapping[Expression, builtins.int]] = None, admit_straight_path: builtins.bool = False, admit_prescribed_path: builtins.bool = False, scales: typing.Optional[typing.Mapping[Expression, Expression]] = None, control: typing.Optional[ComputationControl] = None) -> TransportResult:
        r"""
        A true cache hit needs no admission. Other points require an explicitly
        admitted regular affine path or, with continuation declarations, an
        explicitly admitted prescribed homotopy. These admissions are separate.
        """

@typing.final
class LaurentExpansion:
    r"""
    Epsilon coefficients with independent-fit evidence and absolute comparison errors.
    """
    @property
    def absolute_errors(self) -> typing.Optional[builtins.dict[builtins.int, Float]]:
        r"""
        Absolute propagated uncertainty for projected targets; absent for standalone fits.
        """
    @property
    def evidence_kind(self) -> builtins.str: ...
    @property
    def coefficients(self) -> builtins.dict[builtins.int, ComplexFloat]: ...
    @property
    def verified_digits(self) -> typing.Optional[builtins.int]: ...
    @property
    def working_bits(self) -> builtins.int: ...
    @property
    def samples(self) -> builtins.int: ...
    @property
    def validation_samples(self) -> builtins.int: ...
    @property
    def refinements(self) -> builtins.int: ...
    @property
    def comparison_errors(self) -> builtins.dict[builtins.int, Float]: ...
    @staticmethod
    def fit(samples: typing.Sequence[Expression], values: typing.Sequence[ComplexFloat | Float | builtins.int | builtins.float | builtins.str | decimal.Decimal | builtins.complex | tuple[Float | builtins.int | builtins.float | builtins.str | decimal.Decimal, Float | builtins.int | builtins.float | builtins.str | decimal.Decimal]], leading: builtins.int, last: builtins.int, *, working_digits: builtins.int = 80) -> LaurentExpansion:
        r"""
        Polynomial interpolation alone does not certify the fitted coefficients.
        """

class NumericalError(EvaluationError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

class PrecisionError(AccuracyError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class PreparedIntegralFamily:
    r"""
    A derivative-closed physical family that can generate its own integration boundaries.
    """
    @property
    def basis(self) -> builtins.list[builtins.list[builtins.int]]: ...
    @property
    def nonzero_conditions(self) -> builtins.list[Expression]: ...
    @property
    def target_reductions(self) -> builtins.list[builtins.list[tuple[builtins.list[builtins.int], Expression]]]: ...
    def required_master_range(self, point: typing.Mapping[Expression, Expression], leading: builtins.int, last: builtins.int) -> tuple[builtins.int, builtins.int]:
        r"""
        Required master epsilon orders, accounting for poles in target reduction coefficients.
        """
    def project_targets(self, result: TransportResult, leading: builtins.int, last: builtins.int, *, digits: typing.Optional[builtins.int] = None) -> builtins.list[LaurentExpansion]:
        r"""
        Apply exact target reductions to a retained master result, propagating its uncertainty.
        """
    def generate_boundary(self, cache: BoundaryCache, point: typing.Mapping[Expression, Expression], *, last: builtins.int = 0, extra_digits: builtins.int = 10, control: typing.Optional[ComputationControl] = None) -> TransportResult:
        r"""
        Compute and verify fresh auxiliary-mass boundary values, then insert them atomically.
        """
    def transport(self, cache: BoundaryCache, destination: typing.Mapping[Expression, Expression], leading: builtins.int, last: builtins.int, *, admit_straight_path: builtins.bool = False, scales: typing.Optional[typing.Mapping[Expression, Expression]] = None, control: typing.Optional[ComputationControl] = None) -> TransportResult:
        r"""
        Transport the common master basis; target reductions remain available separately.
        """

class ReductionError(EvaluationError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class ReductionTables:
    r"""
    Exact supplied reductions bound to one ordered family and parameter domain.
    Auxiliary and recursive families require their own explicitly admitted tables.
    """
    def __new__(cls, name: builtins.str = 'supplied reductions') -> ReductionTables: ...
    def with_family(self, family: IntegralFamily, epsilon: Expression, rules: typing.Sequence[tuple[typing.Sequence[builtins.int], typing.Sequence[tuple[typing.Sequence[builtins.int], Expression]]]], residuals: typing.Sequence[typing.Sequence[builtins.int]], *, nonzero_conditions: typing.Optional[typing.Sequence[Expression]] = None, physical_propagators: typing.Optional[builtins.int] = None, dimension: builtins.int = 4) -> ReductionTables:
        r"""
        Return a new collection containing this table; existing scopes cannot be replaced.
        """

class ResourceLimitError(EvaluationError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...

@typing.final
class TransportResult:
    r"""
    Numerical values and evidence for an ordinary or physical transport result.
    """
    @property
    def provenance(self) -> typing.Optional[builtins.str]: ...
    @property
    def root_sheets(self) -> builtins.dict[Expression, builtins.int]:
        r"""
        Discrete root signs relative to the principal root at this exact point.
        """
    @property
    def elapsed_nanoseconds(self) -> builtins.int:
        r"""
        Wall time in integer nanoseconds, including cache-lock wait; zero for cache inspection.
        """
    @property
    def attempted_starting_points(self) -> builtins.list[builtins.dict[Expression, Expression]]:
        r"""
        Compatible sources actually attempted, in selection order.
        """
    @property
    def source_attempt_outcomes(self) -> builtins.list[builtins.str]: ...
    @property
    def source_attempt_costs(self) -> builtins.list[Float]: ...
    @property
    def point(self) -> typing.Optional[ComplexFloat]: ...
    @property
    def coordinates(self) -> builtins.dict[Expression, Expression]: ...
    @property
    def starting_coordinates(self) -> builtins.dict[Expression, Expression]: ...
    @property
    def coefficients(self) -> builtins.list[builtins.list[ComplexFloat]]:
        r"""
        Rows are ordered epsilon powers; columns are basis components.
        """
    @property
    def leading_power(self) -> builtins.int: ...
    @property
    def comparison_errors(self) -> builtins.list[builtins.list[Float]]: ...
    @property
    def verified_digits(self) -> typing.Optional[builtins.int]: ...
    @property
    def input_verified_digits(self) -> typing.Optional[builtins.int]: ...
    @property
    def working_bits(self) -> builtins.int: ...
    @property
    def steps(self) -> builtins.int: ...
    @property
    def rejected_steps(self) -> builtins.int: ...
    @property
    def predicate_evaluations(self) -> builtins.int: ...
    @property
    def rational_trials(self) -> builtins.int: ...
    @property
    def rational_steps(self) -> builtins.int: ...
    @property
    def rational_fallbacks(self) -> builtins.int: ...
    @property
    def last_rational_fallback(self) -> typing.Optional[builtins.str]: ...
    @property
    def fundamental_boundary_charts(self) -> builtins.int: ...
    @property
    def fundamental_boundary_fallback(self) -> typing.Optional[builtins.str]: ...
    @property
    def fundamental_boundary_retry(self) -> typing.Optional[builtins.str]: ...
    @property
    def conditioning_digits(self) -> typing.Optional[builtins.int]: ...
    @property
    def inserted_points(self) -> builtins.int: ...
    @property
    def cache_hit(self) -> builtins.bool: ...
    @property
    def identity(self) -> typing.Optional[builtins.str]: ...

class UnsupportedInputError(EvaluationError):
    r"""
    Numerical integration failure; see the exception message for context.
    """
    ...
