# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import collections.abc
import symbolica
import symbolica.community.hepkit
import typing
from symbolica.community.hepkit import FeynmanDiagram, Kinematics
from symbolica.core import Expression

@typing.final
class Chart:
    r"""
    Original chart ordinals and their retained native representative/kernel association.
    """
    @property
    def source_index(self) -> builtins.int: ...
    @property
    def representative(self) -> builtins.int: ...
    @property
    def representative_permutation(self) -> builtins.list[builtins.int]:
        r"""
        Permutes this chart's target coordinates into its representative's coordinates.
        """
    @property
    def kernel_sector(self) -> typing.Optional[builtins.int]:
        r"""
        None means no numerical kernel at the requested orders: exact, cancelled,
        or truncated. No separate per-chart exact coefficients are retained.
        """
    @property
    def coordinates(self) -> CoordinateMap: ...
    @property
    def geometry(self) -> SectorMap: ...
    @property
    def pre_subtraction(self) -> typing.Optional[PreSubtractionMetadata]:
        r"""
        Source-chart endpoint powers before symmetry, multiplicity and subtraction.
        None denotes an older artifact without this retained record.
        """
    def _repr_html_(self, slf: Chart) -> builtins.str: ...

@typing.final
class CoefficientExpansionSnapshot:
    r"""
    Native per-representative coefficient work for the current or last attempt.
    """
    @property
    def sector(self) -> builtins.int:
        r"""
        Zero-based representative being processed or most recently completed.
        """
    @property
    def requested_method(self) -> builtins.str: ...
    @property
    def effective_method(self) -> builtins.str:
        r"""
        Physical also identifies an exact unregulated-endpoint fallback.
        """
    @property
    def stage(self) -> builtins.str: ...
    @property
    def attempt(self) -> builtins.int:
        r"""
        One-based native attempt; zero means admission or exact physical fallback.
        """
    @property
    def relative_width(self) -> builtins.int:
        r"""
        Native relative width; zero has the same pre-attempt/fallback meaning.
        This is not an absolute Laurent cutoff.
        """
    @property
    def formal_pieces(self) -> builtins.int:
        r"""
        Named-composition pieces in this attempt; zero for physical fallback.
        """
    @property
    def requests(self) -> CoefficientRequestCounts: ...
    def _repr_html_(self, slf: CoefficientExpansionSnapshot) -> builtins.str: ...

@typing.final
class CoefficientRequestCounts:
    r"""
    Native representation counts, reset at each coefficient-series attempt.
    """
    @property
    def source_bodies(self) -> builtins.int: ...
    @property
    def unique_requests(self) -> builtins.int: ...
    @property
    def cached_partials(self) -> builtins.int: ...
    @property
    def aliases(self) -> builtins.int: ...
    @property
    def interleaved_requests(self) -> builtins.int: ...
    @property
    def fallback_requests(self) -> builtins.int: ...
    def _repr_html_(self, slf: CoefficientRequestCounts) -> builtins.str: ...

@typing.final
class CompactCoefficient:
    r"""
    A retained Symbolica alias root and definitions, without restoring a full expression.
    """
    @property
    def order(self) -> builtins.int:
        r"""
        Signed epsilon order of this possibly complex generated coefficient.
        Compiled kernels may split it into separate real/imaginary components.
        """
    @property
    def generation_mode(self) -> builtins.str:
        r"""
        Actual native sector route; a numerical-dual request can retain a symbolic fallback.
        """
    @property
    def root(self) -> Expression: ...
    @property
    def alias_count(self) -> builtins.int:
        r"""
        Stored definitions for this coefficient; definitions may be shared with others.
        """
    @property
    def aliases(self) -> builtins.list[tuple[Expression, Expression]]:
        r"""
        Alias/definition pairs in native Atom order. Definitions may reference aliases.
        Read only for selected detail; this does not inline or expand any expression.
        """
    def expression(self) -> Expression:
        r"""
        Explicitly materialize an actual coefficient through its native owner.
        Numerical-dual sectors cache full expressions on this explicit request;
        passive views retain only the compact recipe root and aliases.
        """
    def _repr_html_(self, slf: CompactCoefficient) -> builtins.str: ...

@typing.final
class CompilationSettings:
    @property
    def backend(self) -> builtins.str: ...
    @property
    def horner_iterations(self) -> builtins.int: ...
    @property
    def cpe_rounds(self) -> typing.Optional[builtins.int]: ...
    @property
    def cores(self) -> builtins.int: ...
    def _repr_html_(self) -> builtins.str: ...
    def __new__(cls, *, backend: builtins.str = 'eager', horner_iterations: builtins.int = 10, cpe_rounds: typing.Optional[builtins.int] = 1000, cores: builtins.int = 1, max_horner_scheme_variables: builtins.int = 500, max_common_pair_cache_entries: builtins.int = 1000000, max_common_pair_distance: builtins.int = 1000, verbose: builtins.bool = False, direct_translation: builtins.bool = True) -> CompilationSettings:
        r"""
        Eager execution is the notebook default on every host. None means unlimited CPE rounds.
        """
    def to_json(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class CoordinateMap:
    r"""
    Native density pullback before endpoint subtraction, including its positive measure.
    """
    @property
    def source_parameters(self) -> builtins.list[Expression]: ...
    @property
    def target_parameters(self) -> builtins.list[Expression]: ...
    @property
    def images(self) -> builtins.list[Expression]: ...
    @property
    def measure_jacobian(self) -> Expression:
        r"""
        Positive real density factor, not an oriented/complex determinant.
        A projective map is gauge-fixed, not a normalized simplex parameterization.
        """
    @property
    def source_domain(self) -> builtins.str: ...
    @property
    def projective_fixed_parameter(self) -> typing.Optional[builtins.int]: ...
    def _repr_html_(self, slf: CoordinateMap) -> builtins.str: ...

@typing.final
class DiscreteSectorAllocation:
    r"""
    Selection probability in the native discrete grid and global points per batch.
    """
    @property
    def probability(self) -> builtins.float: ...
    @property
    def points_per_batch(self) -> builtins.int: ...
    def _repr_html_(self, slf: DiscreteSectorAllocation) -> builtins.str: ...

@typing.final
class DomainAssessment:
    r"""
    The native domain and threshold policy, including historical assessments.
    """
    @property
    def domain(self) -> builtins.str: ...
    @property
    def branch_policy(self) -> builtins.str: ...
    @property
    def caller_asserted(self) -> builtins.bool: ...
    @property
    def relies_on_assertion(self) -> builtins.bool: ...
    @property
    def parameters(self) -> builtins.list[Expression]: ...
    @property
    def factors(self) -> builtins.list[FactorAssessment]: ...
    def _repr_html_(self, slf: DomainAssessment) -> builtins.str: ...

@typing.final
class EndpointPower:
    r"""
    Exact b + c epsilon power and required Taylor coefficients; not a pole count.
    """
    @property
    def parameter(self) -> Expression: ...
    @property
    def exponent(self) -> Expression: ...
    @property
    def constant(self) -> Expression: ...
    @property
    def slope(self) -> Expression: ...
    @property
    def subtraction_count(self) -> builtins.int:
        r"""
        Required endpoint Taylor coefficients; vanishing boundary terms may cancel.
        """
    def _repr_html_(self, slf: EndpointPower) -> builtins.str: ...

@typing.final
class EvaluationDiagnostics:
    r"""
    Native caller-aggregated evaluation counters, including failed attempts.
    """
    @property
    def f64_points(self) -> builtins.int: ...
    @property
    def double_float_points(self) -> builtins.int: ...
    @property
    def arbitrary_points(self) -> builtins.int: ...
    @property
    def unstable_points(self) -> builtins.int: ...
    @property
    def cutoff_zero_points(self) -> builtins.int: ...
    @property
    def unclassified_points(self) -> builtins.int: ...
    @property
    def f64_timing(self) -> EvaluatorTiming: ...
    @property
    def double_float_timing(self) -> EvaluatorTiming: ...
    @property
    def arbitrary_timing(self) -> EvaluatorTiming: ...
    @property
    def evaluations(self) -> builtins.int: ...
    @property
    def conditioning_checks(self) -> builtins.int: ...
    @property
    def rescues(self) -> builtins.int: ...
    @property
    def max_precision_bits(self) -> builtins.int: ...
    @property
    def failures(self) -> builtins.int: ...
    @property
    def weighted_checks(self) -> builtins.int: ...
    @property
    def additional_replays(self) -> builtins.int: ...
    def _repr_html_(self, slf: EvaluationDiagnostics) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class EvaluatorOperations:
    r"""
    Native shared evaluator counts; these are not optimized machine-operation counts.
    """
    @property
    def additions(self) -> builtins.int: ...
    @property
    def multiplications(self) -> builtins.int: ...
    @property
    def inversions(self) -> builtins.int: ...
    @property
    def function_calls(self) -> builtins.int: ...
    def _repr_html_(self, slf: EvaluatorOperations) -> builtins.str: ...

@typing.final
class EvaluatorStatistics:
    r"""
    Complete shared sector evaluator size on the current backend.
    """
    @property
    def version(self) -> builtins.int: ...
    @property
    def backend(self) -> builtins.str: ...
    @property
    def arithmetic(self) -> builtins.str: ...
    @property
    def inputs(self) -> builtins.int: ...
    @property
    def outputs(self) -> builtins.int:
        r"""
        Shared evaluator outputs, before complex outputs split into real/imaginary components.
        """
    @property
    def exact_program_bytes(self) -> builtins.int: ...
    @property
    def operations(self) -> EvaluatorOperations:
        r"""
        Symbolica exact-program operations before SymJIT lowering/optimization.
        """
    @property
    def symjit_ir_bytes(self) -> typing.Optional[builtins.int]:
        r"""
        Actual compressed SymJIT application bytes, not machine-code size; None for interpreter.
        """
    def _repr_html_(self, slf: EvaluatorStatistics) -> builtins.str: ...

@typing.final
class EvaluatorTiming:
    @property
    def calls(self) -> builtins.int:
        r"""
        Evaluated points, including speculative or repeated numerical attempts.
        """
    @property
    def nanoseconds(self) -> builtins.int: ...
    @property
    def matrix_invocations(self) -> builtins.int: ...
    @property
    def matrix_points(self) -> builtins.int: ...
    def _repr_html_(self, slf: EvaluatorTiming) -> builtins.str: ...

@typing.final
class FactorAssessment:
    @property
    def term_index(self) -> builtins.int: ...
    @property
    def factor_index(self) -> builtins.int: ...
    @property
    def polynomial(self) -> Expression: ...
    @property
    def exponent(self) -> Expression: ...
    @property
    def certificate(self) -> builtins.str: ...
    def _repr_html_(self, slf: FactorAssessment) -> builtins.str: ...

@typing.final
class FormulaPreparationSnapshot:
    r"""
    Coordinator-owned counts for unique subtraction-formula precomputation.
    """
    @property
    def completed(self) -> builtins.int:
        r"""
        Successfully completed unique formula builds.
        """
    @property
    def total(self) -> builtins.int:
        r"""
        Distinct formula keys discovered for this generation.
        """
    @property
    def sectors(self) -> builtins.int:
        r"""
        Eligible sectors which use these formulas.
        """
    @property
    def reused(self) -> builtins.int:
        r"""
        Shared uses (eligible sectors minus distinct keys), not cache lookups.
        """
    def _repr_html_(self, slf: FormulaPreparationSnapshot) -> builtins.str: ...

@typing.final
class GeneratedIntegral:
    @property
    def mode(self) -> builtins.str:
        r"""
        Requested native generation lane, retained without recomputing sectors.
        """
    @property
    def subtraction(self) -> builtins.str: ...
    @property
    def runtime_parameters(self) -> builtins.list[Expression]: ...
    @property
    def model_parameter_defaults(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        Model-card defaults are human metadata, never automatically bound.
        """
    @property
    def runtime_parameter_defaults(self) -> dict:
        r"""
        Explicitly inspectable defaults keyed by the actual native runtime symbols.
        """
    @property
    def sectors(self) -> builtins.list[GeneratedSector]:
        r"""
        Immutable native sector views; coefficients remain compact until requested.
        """
    @property
    def metadata(self) -> GenerationMetadata:
        r"""
        Retained native domain and chart metadata, without evaluating the integral.
        """
    @property
    def orders(self) -> builtins.list[builtins.int]: ...
    @property
    def sector_count(self) -> builtins.int: ...
    @property
    def exact_coefficients(self) -> builtins.list[Expression]: ...
    def snapshot(self) -> GenerationSnapshot: ...
    def compile(self, *, backend: str = 'eager', settings: typing.Optional[symbolica.community.hepkit.sector_decomposition.CompilationSettings] = None, observer: typing.Optional[typing.Callable[[symbolica.community.hepkit.sector_decomposition.GenerationSnapshot], typing.Optional[bool]]] = None, progress: typing.Union[typing.Literal["auto"], typing.Callable[[symbolica.community.hepkit.sector_decomposition.GenerationSnapshot], typing.Optional[bool]], None] = 'auto') -> symbolica.community.hepkit.sector_decomposition.Kernels:
        r"""
        Compile native evaluators without creating or advancing a session.

        Auto progress uses HEPKit's marimo presenter unless observer is supplied;
        None disables it. Callables receive all snapshots, observer first.
        None/True continues, False cancels; original exceptions propagate.
        """
    def _repr_html_(self, slf: GeneratedIntegral) -> builtins.str: ...

@typing.final
class GeneratedSector:
    r"""
    A numerical sector at its native kernel-association index, with shared ownership.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        Native numerical-sector index used by Chart.kernel_sector.
        """
    @property
    def generation_mode(self) -> builtins.str:
        r"""
        Actual route used for this sector, including explicit local symbolic fallback.
        """
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def parameters(self) -> builtins.list[Expression]: ...
    @property
    def coefficient_count(self) -> builtins.int: ...
    @property
    def alias_counts(self) -> builtins.list[builtins.int]:
        r"""
        Stored alias definitions per coefficient, not a unique count across coefficients.
        """
    @property
    def cancellation_degree(self) -> builtins.int: ...
    @property
    def conditioning_basis(self) -> builtins.str:
        r"""
        Provenance of conditioning profiles, not a floating-point error certificate.
        """
    @property
    def cancellation_terms(self) -> builtins.list[builtins.list[builtins.int]]: ...
    @property
    def map(self) -> SectorMap: ...
    @property
    def aliased_coefficients(self) -> builtins.list[CompactCoefficient]:
        r"""
        Native complex coefficient roots/definitions aligned with GeneratedIntegral.orders.
        This creates cheap views; no coefficients are materialized or expanded.
        """
    def _repr_html_(self, slf: GeneratedSector) -> builtins.str: ...

@typing.final
class GenerationMetadata:
    r"""
    Retained domain and chart associations; no decomposition is repeated by inspection.
    """
    @property
    def domain(self) -> DomainAssessment: ...
    @property
    def charts(self) -> builtins.list[Chart]: ...
    def _repr_html_(self, slf: GenerationMetadata) -> builtins.str: ...

@typing.final
class GenerationSession:
    @property
    def mode(self) -> builtins.str: ...
    @property
    def subtraction(self) -> builtins.str: ...
    @property
    def complete(self) -> builtins.bool: ...
    @property
    def failed(self) -> typing.Optional[builtins.str]: ...
    @property
    def generated(self) -> typing.Optional[GeneratedIntegral]: ...
    @property
    def kernels(self) -> typing.Optional[Kernels]: ...
    def step(self, max_units: builtins.int = 1, *, observer: typing.Optional[typing.Any] = None) -> GenerationSnapshot:
        r"""
        Run at most max_units indivisible native units on this caller's thread.
        False observers and KeyboardInterrupt pause; already completed work is retained.
        Numerical/algebra errors are terminal and expose no partial kernels.
        """
    def snapshot(self) -> GenerationSnapshot: ...
    def __repr__(self) -> builtins.str: ...
    def _repr_html_(self, slf: GenerationSession) -> builtins.str: ...

@typing.final
class GenerationSnapshot:
    r"""
    Generation progress copied from the native caller-owned observer.
    """
    @property
    def stage(self) -> builtins.str:
        r"""
        Stable snake_case name of the native generation stage.
        """
    @property
    def completed(self) -> builtins.int: ...
    @property
    def total(self) -> typing.Optional[builtins.int]: ...
    @property
    def sectors(self) -> builtins.int: ...
    @property
    def kernels(self) -> builtins.int: ...
    @property
    def elapsed_seconds(self) -> builtins.float: ...
    @property
    def timings(self) -> GenerationTimings: ...
    @property
    def coefficient_expansion(self) -> typing.Optional[CoefficientExpansionSnapshot]:
        r"""
        Current or last named-coefficient attempt; None for physical-only generation.
        """
    @property
    def formula_preparation(self) -> typing.Optional[FormulaPreparationSnapshot]:
        r"""
        Known unique-formula counts; None before discovery or without this phase.
        """
    @property
    def detail(self) -> builtins.str: ...
    def _repr_html_(self, slf: GenerationSnapshot) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class GenerationTimings:
    r"""
    Native observed generation wall times in seconds.

    The total ends after preparing kernels and metadata, before artifact writing.
    """
    @property
    def input_seconds(self) -> builtins.float: ...
    @property
    def parametrization_seconds(self) -> builtins.float: ...
    @property
    def domain_seconds(self) -> builtins.float: ...
    @property
    def geometry_seconds(self) -> builtins.float: ...
    @property
    def mapping_seconds(self) -> builtins.float: ...
    @property
    def formula_preparation_seconds(self) -> typing.Optional[builtins.float]:
        r"""
        Distinct precomputation wall time, excluding paused session time.
        None means the phase was not observed, not a zero-duration measurement.
        """
    @property
    def symmetry_seconds(self) -> builtins.float: ...
    @property
    def subtraction_seconds(self) -> builtins.float: ...
    @property
    def laurent_seconds(self) -> builtins.float: ...
    @property
    def coefficient_expansion_seconds(self) -> builtins.float:
        r"""
        Entire named phase, including any exact physical fallback.
        """
    @property
    def compilation_seconds(self) -> builtins.float: ...
    @property
    def total_seconds(self) -> builtins.float: ...
    def _repr_html_(self, slf: GenerationTimings) -> builtins.str: ...

@typing.final
class HavanaDiscreteSession:
    r"""
    Caller-owned native sector importance sampling. Pilot pauses retain this object;
    persistent checkpoints require frozen production. No worker pool is created.
    """
    @property
    def complete(self) -> builtins.bool:
        r"""
        Whether this pilot epoch or production allocation has completed.
        """
    @property
    def stage(self) -> builtins.str: ...
    @property
    def checkpoint_available(self) -> builtins.bool: ...
    @property
    def settings(self) -> HavanaDiscreteSettings: ...
    @property
    def sector_probabilities(self) -> builtins.list[tuple[builtins.int, builtins.float]]:
        r"""
        (Native sector id, current selection probability) in native problem order.
        """
    def checkpoint(self) -> bytes:
        r"""
        Persist accepted frozen-production batches and native replay state.
        Pilot training is deliberately not serialized; retain the session to resume it.
        """
    def observation(self) -> IntegrationObservation: ...
    def live_observation(self) -> LiveObservation:
        r"""
        Native point-statistics preview, separate from accepted complete-batch covariance.
        """
    def snapshot(self) -> IntegrationSnapshot: ...
    def adapt_pilot(self, *, discrete_learning_rate: builtins.float = 1.0, continuous_learning_rate: builtins.float = 1.0) -> IntegrationSnapshot:
        r"""
        Adapt only a completed pilot and start another independent native pilot epoch.
        """
    def freeze_production(self, *, points_per_batch: builtins.int, batches: builtins.int, discrete_learning_rate: builtins.float = 1.0, continuous_learning_rate: builtins.float = 1.0) -> IntegrationSnapshot:
        r"""
        Adapt a completed pilot, freeze both grids, and discard all pilot estimates.
        """
    def step(self, max_batches: builtins.int = 1, *, evaluation_batch_size: builtins.int = 256, observer: typing.Optional[typing.Any] = None) -> IntegrationSnapshot:
        r"""
        Execute at most max_batches. False from observer pauses after an accepted
        global batch. Interrupted batches are retried, without partial statistics.
        """
    def _repr_html_(self, slf: HavanaDiscreteSession) -> builtins.str: ...

@typing.final
class HavanaDiscreteSettings:
    r"""
    Native global-batch allocation and discrete/continuous Havana grid settings.
    """
    @property
    def points_per_batch(self) -> builtins.int: ...
    @property
    def batches(self) -> builtins.int: ...
    @property
    def seed(self) -> builtins.int: ...
    @property
    def bins(self) -> builtins.int: ...
    @property
    def minimum_probability_density(self) -> builtins.float: ...
    @property
    def maximum_sector_probability_ratio(self) -> builtins.float: ...
    def __new__(cls, *, points_per_batch: builtins.int = 4096, batches: builtins.int = 64, seed: builtins.int = 0, bins: builtins.int = 32, minimum_probability_density: builtins.float = 0.01, maximum_sector_probability_ratio: builtins.float = 100.0) -> HavanaDiscreteSettings: ...
    def _repr_html_(self, slf: HavanaDiscreteSettings) -> builtins.str: ...

@typing.final
class Integral:
    r"""
    Native diagram, assumptions and explicit normalized loop measure.
    """
    @property
    def regulator(self) -> Expression: ...
    @property
    def dimension(self) -> Expression: ...
    @property
    def powers(self) -> builtins.list[tuple[builtins.int, builtins.int]]: ...
    def generate(self, max_order: int = 0, *, coefficient_expansion: str = 'full_expression', mode: str = 'symbolic', subtraction: str = 'taylor', observer: typing.Optional[typing.Callable[[symbolica.community.hepkit.sector_decomposition.GenerationSnapshot], typing.Optional[bool]]] = None, progress: typing.Union[typing.Literal["auto"], typing.Callable[[symbolica.community.hepkit.sector_decomposition.GenerationSnapshot], typing.Optional[bool]], None] = 'auto') -> symbolica.community.hepkit.sector_decomposition.GeneratedIntegral:
        r"""
        Generate native sectors without compilation or numerical integration.

        Auto progress uses HEPKit's marimo presenter unless observer is supplied;
        None disables it. Callables receive all snapshots, observer first.
        None/True continues, False cancels; original exceptions propagate.
        """
    def generation_session(self, max_order: int = 0, *, coefficient_expansion: str = 'coefficient_series', mode: str = 'symbolic', subtraction: str = 'taylor', compilation_settings: typing.Optional[symbolica.community.hepkit.sector_decomposition.CompilationSettings] = None, runtime_parameters: typing.Optional[list[symbolica.Expression]] = None) -> symbolica.community.hepkit.sector_decomposition.GenerationSession:
        r"""
        Create retained caller-stepped generation and compilation; construction performs no symbolic work.
        """
    def __new__(cls, diagram: FeynmanDiagram, kinematics: Kinematics, *, regulator: Expression, dimension: typing.Optional[Expression] = None, powers: typing.Optional[typing.Mapping[builtins.int, builtins.int]] = None, scalar_values: typing.Optional[dict] = None, auxiliary_momenta: typing.Optional[typing.Sequence[Expression]] = None, measure_multiplier: typing.Optional[Expression] = None, runtime_parameters: typing.Optional[typing.Sequence[Expression]] = None, model_parameters: builtins.str = 'runtime') -> Integral:
        r"""
        Kinematics retains its symbolic tensor dimension; dimension defaults to 4-2*regulator.
        """
    def _repr_html_(self, slf: Integral) -> builtins.str: ...

@typing.final
class IntegrationObservation:
    @property
    def snapshot(self) -> IntegrationSnapshot: ...
    @property
    def total(self) -> typing.Optional[VectorEstimate]: ...
    @property
    def sectors(self) -> builtins.list[SectorContribution]: ...
    @property
    def exact_coefficients(self) -> builtins.list[builtins.float]: ...
    @property
    def orders(self) -> builtins.list[builtins.int]: ...
    @property
    def components(self) -> builtins.list[builtins.str]: ...
    @property
    def replica_relation(self) -> builtins.str: ...
    def _repr_html_(self, slf: IntegrationObservation) -> builtins.str: ...
    def to_json(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class IntegrationSnapshot:
    r"""
    Coverage and estimates from the native caller-driven integration session.
    """
    @property
    def method(self) -> builtins.str: ...
    @property
    def stage(self) -> builtins.str: ...
    @property
    def completed_points(self) -> builtins.int: ...
    @property
    def planned_points(self) -> builtins.int: ...
    @property
    def complete_sectors(self) -> builtins.int: ...
    @property
    def sectors(self) -> builtins.list[SectorSnapshot]: ...
    @property
    def uncertainty(self) -> builtins.str:
        r"""
        Native validity state; statistical_failure retains its reason in uncertainty_detail.
        """
    @property
    def uncertainty_detail(self) -> typing.Optional[builtins.str]:
        r"""
        Native failure explanation, when the uncertainty state is statistical_failure.
        """
    @property
    def estimate(self) -> typing.Optional[VectorEstimate]:
        r"""
        Native full Laurent vector, or None when no valid estimate is available.
        """
    @property
    def worker_seconds(self) -> builtins.float:
        r"""
        Sum of worker execution times; caller wall time is separate.
        """
    @property
    def stop_reason(self) -> typing.Optional[builtins.str]:
        r"""
        Native caller-supplied stopping reason, or None while none is recorded.
        """
    @property
    def stop_detail(self) -> typing.Optional[builtins.str]:
        r"""
        Native failure explanation, when stop_reason is numerical_failure.
        """
    @property
    def evaluation_diagnostics(self) -> typing.Optional[EvaluationDiagnostics]: ...
    def _repr_html_(self, slf: IntegrationSnapshot) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Kernels:
    r"""
    Compiled native evaluator owners. Each session owns one lazy execution context.
    """
    @property
    def runtime_parameters(self) -> builtins.list[Expression]: ...
    @property
    def parameters_bound(self) -> builtins.bool: ...
    @property
    def compilation_settings(self) -> CompilationSettings: ...
    @property
    def stability_settings(self) -> StabilitySettings: ...
    @property
    def content_id(self) -> builtins.str: ...
    @property
    def orders(self) -> builtins.list[builtins.int]: ...
    @property
    def components(self) -> builtins.list[builtins.str]: ...
    @property
    def sector_count(self) -> builtins.int: ...
    @property
    def sector_statistics(self) -> builtins.list[EvaluatorStatistics]:
        r"""
        Actual complete-vector evaluator records, aligned with native kernel sectors.
        """
    @property
    def exact_coefficients(self) -> builtins.list[builtins.float]: ...
    @property
    def backend(self) -> builtins.str: ...
    def with_parameters(self, values: dict, *, stability: typing.Optional[StabilitySettings] = None) -> Kernels:
        r"""
        Bind an explicit complete physical point on independently owned native evaluators.
        """
    def with_stability(self, settings: StabilitySettings) -> Kernels: ...
    def to_bytes(self) -> bytes:
        r"""
        Persist the library's native portable program/metadata codec, excluding machine code.
        """
    @staticmethod
    def from_bytes(artifact: bytes) -> Kernels:
        r"""
        Validate native programs and construct evaluators for the current host backend.
        """
    def snapshot(self) -> GenerationSnapshot: ...
    def session(self, settings: typing.Optional[QmcSettings] = None) -> QmcSession: ...
    def restore(self, checkpoint: bytes) -> QmcSession:
        r"""
        Restore complete accepted packages and replay state against these exact kernels.
        """
    def mc_session(self, settings: typing.Optional[HavanaDiscreteSettings] = None, *, pilot: builtins.bool = False, sector_probabilities: typing.Optional[typing.Sequence[builtins.float]] = None) -> HavanaDiscreteSession:
        r"""
        Native sector-importance Havana, with a caller-controlled pilot or frozen production.
        """
    def restore_mc(self, checkpoint: bytes) -> HavanaDiscreteSession:
        r"""
        Restore only a native frozen-production discrete Havana checkpoint.
        """
    def _repr_html_(self, slf: Kernels) -> builtins.str: ...

@typing.final
class LiveEstimate:
    @property
    def mean(self) -> typing.Optional[builtins.list[builtins.float]]: ...
    @property
    def standard_error(self) -> typing.Optional[builtins.list[builtins.float]]: ...
    @property
    def points(self) -> builtins.int: ...
    @property
    def replicas(self) -> builtins.int: ...
    @property
    def status(self) -> builtins.str: ...
    def _repr_html_(self, slf: LiveEstimate) -> builtins.str: ...

@typing.final
class LiveObservation:
    @property
    def source(self) -> builtins.str: ...
    @property
    def stage(self) -> builtins.str: ...
    @property
    def total(self) -> LiveEstimate: ...
    @property
    def sectors(self) -> builtins.list[LiveSector]: ...
    @property
    def orders(self) -> builtins.list[builtins.int]: ...
    @property
    def components(self) -> builtins.list[builtins.str]: ...
    def _repr_html_(self, slf: LiveObservation) -> builtins.str: ...
    def to_json(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LiveSector:
    @property
    def id(self) -> builtins.int: ...
    @property
    def estimate(self) -> LiveEstimate: ...
    def _repr_html_(self, slf: LiveSector) -> builtins.str: ...

@typing.final
class PreSubtractionMetadata:
    r"""
    Mapped density before symmetry, multiplicity, endpoint subtraction or expansion.
    """
    @property
    def version(self) -> builtins.int: ...
    @property
    def regulator(self) -> Expression: ...
    @property
    def terms(self) -> builtins.list[PreSubtractionTerm]: ...
    def _repr_html_(self, slf: PreSubtractionMetadata) -> builtins.str: ...

@typing.final
class PreSubtractionTerm:
    r"""
    One mapped term; its potentially large regular body is never materialized.
    """
    @property
    def prefactor(self) -> Expression: ...
    @property
    def regular_expression_basis(self) -> builtins.str:
        r"""
        Whether regular_expression_bytes describes the source or mapped Atom.
        """
    @property
    def regular_expression_bytes(self) -> builtins.int:
        r"""
        Native regular Atom storage in regular_expression_basis, not evaluator size.
        """
    @property
    def powers(self) -> builtins.list[EndpointPower]:
        r"""
        Ordered like this source chart's coordinate target_parameters.
        """
    def _repr_html_(self, slf: PreSubtractionTerm) -> builtins.str: ...

@typing.final
class QmcSession:
    r"""
    Caller-owned bounded execution, with no background loop or worker pool.
    """
    @property
    def complete(self) -> builtins.bool: ...
    @property
    def settings(self) -> QmcSettings: ...
    def _repr_html_(self, slf: QmcSession) -> builtins.str: ...
    def observation(self) -> IntegrationObservation: ...
    def live_observation(self) -> LiveObservation: ...
    def snapshot(self) -> IntegrationSnapshot: ...
    def step(self, max_packages: builtins.int = 1, *, evaluation_batch_size: builtins.int = 256, observer: typing.Optional[typing.Any] = None) -> IntegrationSnapshot:
        r"""
        Execute at most max_packages, returning to the Python caller between steps.
        An observer receives immutable snapshots after accepted packages; False stops this call.
        """
    def checkpoint(self) -> bytes: ...

@typing.final
class QmcSettings:
    @property
    def points(self) -> builtins.int: ...
    @property
    def shifts(self) -> builtins.int: ...
    @property
    def seed(self) -> builtins.int: ...
    @property
    def package_points(self) -> builtins.int: ...
    @property
    def periodization(self) -> builtins.str: ...
    @property
    def rule(self) -> builtins.str: ...
    def _repr_html_(self, slf: QmcSettings) -> builtins.str: ...
    def __new__(cls, *, points: builtins.int = 4096, shifts: builtins.int = 64, seed: builtins.int = 0, package_points: builtins.int = 1024, periodization: builtins.str = 'korobov3', rule: builtins.str = 'kuo_33002') -> QmcSettings:
        r"""
        Democratic QMC uses the native Kuo rule and retains full shift covariance.
        """

@typing.final
class SectorContribution:
    @property
    def id(self) -> builtins.int: ...
    @property
    def completed_points(self) -> builtins.int: ...
    @property
    def planned_points(self) -> typing.Optional[builtins.int]: ...
    @property
    def used_points(self) -> builtins.int: ...
    @property
    def used_replicas(self) -> builtins.int: ...
    @property
    def estimate(self) -> typing.Optional[VectorEstimate]: ...
    @property
    def uncertainty(self) -> builtins.str: ...
    def _repr_html_(self, slf: SectorContribution) -> builtins.str: ...

@typing.final
class SectorMap:
    r"""
    The retained exact integer geometry, with native Numerica-to-Python integer transport.
    """
    @property
    def source_dimension(self) -> builtins.int: ...
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def fixed_parameter(self) -> typing.Optional[builtins.int]: ...
    @property
    def exponent_matrix(self) -> builtins.list[builtins.list[int]]: ...
    @property
    def determinant(self) -> int: ...
    @property
    def jacobian_powers(self) -> builtins.list[int]: ...
    @property
    def factor_valuations(self) -> builtins.list[builtins.list[int]]:
        r"""
        Indices follow deduplicated support order, not uniquely named U/F factors.
        """
    def _repr_html_(self, slf: SectorMap) -> builtins.str: ...

@typing.final
class SectorSnapshot:
    r"""
    Native per-sector work and complete-replica coverage.
    """
    @property
    def id(self) -> builtins.int: ...
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def completed_points(self) -> builtins.int: ...
    @property
    def planned_points(self) -> typing.Optional[builtins.int]: ...
    @property
    def discrete_allocation(self) -> typing.Optional[DiscreteSectorAllocation]:
        r"""
        Current native selection probability and global batch size; no fixed sector quota.
        """
    @property
    def complete_replicas(self) -> builtins.int: ...
    @property
    def planned_replicas(self) -> builtins.int: ...
    @property
    def worker_seconds(self) -> builtins.float: ...
    def _repr_html_(self, slf: SectorSnapshot) -> builtins.str: ...

@typing.final
class StabilitySettings:
    @property
    def mode(self) -> builtins.str: ...
    def _repr_html_(self) -> builtins.str: ...
    def __new__(cls, *, mode: builtins.str = 'distance', f64_distance: builtins.float = 0.001, double_float_distance: builtins.float = 1e-08, large_weight_threshold: typing.Optional[builtins.float] = 0.9, double_float_large_weight_threshold: typing.Optional[builtins.float] = None, unstable_cutoff: typing.Optional[builtins.float] = None, f64_power_thresholds: typing.Optional[typing.Mapping[builtins.str, builtins.float]] = None, double_float_power_thresholds: typing.Optional[typing.Mapping[builtins.str, builtins.float]] = None, unstable_power_thresholds: typing.Optional[typing.Mapping[builtins.str, builtins.float]] = None) -> StabilitySettings: ...
    @staticmethod
    def from_json(value: builtins.str) -> StabilitySettings: ...
    def to_json(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class VectorEstimate:
    r"""
    Native joint Laurent estimate with signed orders and full covariance.

    Returned arrays are independent copies. The bridge does not reconstruct
    uncertainty or combine components, sectors, or orders.
    """
    @property
    def orders(self) -> builtins.list[builtins.int]:
        r"""
        Signed epsilon powers, in exactly the native output order.
        """
    @property
    def components(self) -> builtins.list[builtins.str]:
        r"""
        A real or imag label for each native output entry.
        """
    @property
    def mean(self) -> builtins.list[builtins.float]: ...
    @property
    def standard_error(self) -> builtins.list[builtins.float]: ...
    @property
    def covariance_of_mean(self) -> builtins.list[builtins.float]:
        r"""
        Full row-major covariance of the mean, including inter-order and
        real/imaginary correlations. Entry (i, j) is at i * len(orders) + j.
        """
    @property
    def production_complete(self) -> builtins.bool:
        r"""
        Only a complete production allocation can certify an accuracy stop.
        """
    def _repr_html_(self, slf: VectorEstimate) -> builtins.str: ...
    def meets(self, *, absolute: builtins.float = 0.0, relative: builtins.float = 0.001) -> builtins.bool:
        r"""
        Delegate convergence to the native full-production and vector tolerance check.
        """

def sector_decompose(input: typing.Union[symbolica.community.hepkit.FeynmanDiagram, symbolica.community.hepkit.IntegralFamily], *, regulator: symbolica.Expression, kinematics: typing.Optional[symbolica.community.hepkit.Kinematics] = None, dimension: typing.Optional[symbolica.Expression] = None, powers: typing.Optional[typing.Union[collections.abc.Mapping[int, int], collections.abc.Sequence[int]]] = None, numerator: typing.Optional[symbolica.Expression] = None, scalar_values: typing.Optional[dict[symbolica.Expression, symbolica.Expression]] = None, auxiliary_momenta: typing.Optional[collections.abc.Sequence[symbolica.Expression]] = None, measure_multiplier: typing.Optional[symbolica.Expression] = None, runtime_parameters: typing.Optional[list[symbolica.Expression]] = None, model_parameters: str = 'runtime', max_order: int = 0, coefficient_expansion: str = 'full_expression', mode: str = 'symbolic', subtraction: str = 'taylor', observer: typing.Optional[collections.abc.Callable[[symbolica.community.hepkit.sector_decomposition.GenerationSnapshot], typing.Optional[bool]]] = None, progress: typing.Union[typing.Literal["auto"], typing.Callable[[symbolica.community.hepkit.sector_decomposition.GenerationSnapshot], typing.Optional[bool]], None] = 'auto') -> symbolica.community.hepkit.sector_decomposition.GeneratedIntegral:
    r"""
    Generate from an existing native diagram or an explicitly weighted family.

    Diagrams require kinematics, use their owned numerator/weights, and take an
    optional positive-power mapping by stable edge ID. Families require a signed
    power sequence in native denominator order and a weighted scalar numerator;
    auxiliary slots never default to power one. Kinematics overrides must retain
    original external products after scalar binding, but may add auxiliary data.
    Dimension defaults to 4-2*regulator. Compilation and sessions are explicit.
    progress="auto" shows HEPKit progress in marimo when observer is absent.
    None disables display; a callable receives every snapshot after observer.
    None/True continues, False cancels; original callback exceptions propagate.
    """

def with_diagram_expressions(diagram: FeynmanDiagram, *, numerator: typing.Optional[Expression] = None, projector: typing.Optional[Expression] = None, overall_factor: typing.Optional[Expression] = None) -> FeynmanDiagram:
    r"""
    Copy a complete native diagram, replacing only the supplied expressions.
    Native numerator validation and all graph/model ownership are preserved.
    """


class FastSecDecError(RuntimeError):
    stage: str

class CancelledError(FastSecDecError): ...
