# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from symbolica.core import Expression

@typing.final
class AlgebraicLetter:
    r"""
    Immutable metadata for one formal quadratic-root pair allocated by an
    integration.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        Stable one-based index of this formal root pair.
        """
    @property
    def integration_variable_index(self) -> builtins.int:
        r"""
        Zero-based exact-context index of the integration variable that
        introduced this root pair.
        """
    @property
    def polynomial(self) -> Expression:
        r"""
        Defining polynomial for the quadratic root pair.
        """
    @property
    def leading_coefficient(self) -> Expression:
        r"""
        Leading coefficient of the defining polynomial.
        """
    @property
    def root_sum(self) -> Expression:
        r"""
        Sum of the two formal roots.
        """
    @property
    def root_product(self) -> Expression:
        r"""
        Product of the two formal roots.
        """
    @property
    def discriminant(self) -> Expression:
        r"""
        Discriminant of the defining polynomial.
        """
    @property
    def minus(self) -> Expression:
        r"""
        Native Symbolica expression for the minus root.
        """
    @property
    def plus(self) -> Expression:
        r"""
        Native Symbolica expression for the plus root.
        """
    def __copy__(self) -> AlgebraicLetter: ...
    def __deepcopy__(self, _memo: typing.Any) -> AlgebraicLetter: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class IntegrationOptions:
    r"""
    Options controlling exact hyperlogarithm integration.

    Reduction rules are `(left_hand_side, right_hand_side)` string pairs in
    HyperFLINT's generated MZV-table notation.  They are data-table entries,
    not mathematical input expressions passed through the Python boundary.

    Instances are mutable, compare by value, and support `copy.copy` and
    `copy.deepcopy`. Preparing an input stores an independent copy of the
    options, so later mutations do not affect that prepared object.

    Omitting both MZV arguments selects the standard table embedded in the
    extension. Passing either argument explicitly selects a complete override;
    in particular, `mzv_reductions=[]` disables standard reductions.
    """
    @property
    def check_divergences(self) -> builtins.bool:
        r"""
        Whether to detect non-cancelling endpoint divergences.
        """
    @check_divergences.setter
    def check_divergences(self, value: builtins.bool) -> None: ...
    @property
    def parallel(self) -> builtins.bool:
        r"""
        Whether to parallelize independent shuffle entries deterministically.
        """
    @parallel.setter
    def parallel(self, value: builtins.bool) -> None: ...
    @property
    def introduce_algebraic_letters(self) -> builtins.bool:
        r"""
        Whether the linear-factor layer may introduce algebraic letters.
        """
    @introduce_algebraic_letters.setter
    def introduce_algebraic_letters(self, value: builtins.bool) -> None: ...
    @property
    def close_final_positive_letters(self) -> builtins.bool:
        r"""
        Whether to close positive-real-axis letters after the last variable.
        """
    @close_final_positive_letters.setter
    def close_final_positive_letters(self, value: builtins.bool) -> None: ...
    @property
    def mzv_reductions(self) -> builtins.list[tuple[builtins.str, builtins.str]]:
        r"""
        Exact MZV reduction rules as `(left_hand_side, right_hand_side)` pairs.
        """
    @mzv_reductions.setter
    def mzv_reductions(self, value: builtins.list[tuple[builtins.str, builtins.str]]) -> None: ...
    @property
    def mzv_basis(self) -> builtins.list[builtins.str]:
        r"""
        Symbolica constant names reserved as the active MZV basis.
        """
    @mzv_basis.setter
    def mzv_basis(self, value: builtins.list[builtins.str]) -> None: ...
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __new__(cls, *, check_divergences: builtins.bool = False, parallel: builtins.bool = True, introduce_algebraic_letters: builtins.bool = False, close_final_positive_letters: builtins.bool = True, mzv_reductions: typing.Optional[typing.Sequence[tuple[builtins.str, builtins.str]]] = None, mzv_basis: typing.Optional[typing.Sequence[builtins.str]] = None) -> IntegrationOptions: ...
    def __copy__(self) -> IntegrationOptions:
        r"""
        Return an independent options object.
        """
    def __deepcopy__(self, _memo: typing.Any) -> IntegrationOptions:
        r"""
        Return an independent options object; all fields already own data.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class IntegrationResult:
    r"""
    An inspectable exact integration result.

    Use `expression` to materialize the collected terms as a native Symbolica
    expression.  The direct `integrate` function performs this step for you.
    Instances are immutable and support `copy.copy` and `copy.deepcopy`.
    """
    @property
    def expression(self) -> Expression:
        r"""
        Materialize all collected terms as one normalized Symbolica expression.
        """
    @property
    def integration_variables(self) -> builtins.list[Expression]:
        r"""
        Integration variables in the order in which they were integrated.
        """
    @property
    def indeterminates(self) -> builtins.list[Expression]:
        r"""
        Symbolica indeterminates in the exact polynomial context.
        """
    @property
    def algebraic_letters(self) -> builtins.list[AlgebraicLetter]:
        r"""
        Formal quadratic-root definitions introduced by the integration.
        """
    @property
    def term_count(self) -> builtins.int:
        r"""
        Number of collected coefficient/period-product terms.
        """
    @property
    def algebraic_letter_count(self) -> builtins.int:
        r"""
        Number of formal quadratic-root pairs introduced by integration.
        """
    @property
    def variable_count(self) -> builtins.int:
        r"""
        Number of integration variables in the completed schedule.
        """
    @property
    def indeterminate_count(self) -> builtins.int:
        r"""
        Number of exact Symbolica indeterminates in the result context.
        """
    @property
    def is_zero(self) -> builtins.bool:
        r"""
        Whether the exact result is zero.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of collected coefficient/period-product terms.
        """
    def __copy__(self) -> IntegrationResult: ...
    def __deepcopy__(self, _memo: typing.Any) -> IntegrationResult: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PreparedIntegral:
    r"""
    A lowered Atom input that can be integrated repeatedly without repeating
    Symbolica-to-ring and Hlog conversion.

    Create instances with `integration.prepare`. The object is
    immutable; `copy.copy` and `copy.deepcopy` return independent Python
    handles that share its immutable backing storage.
    """
    @property
    def integration_variables(self) -> builtins.list[Expression]:
        r"""
        Integration variables in their requested order.
        """
    @property
    def indeterminates(self) -> builtins.list[Expression]:
        r"""
        Symbolica indeterminates in the prepared exact polynomial context.
        """
    @property
    def shuffle_term_count(self) -> builtins.int:
        r"""
        Number of shuffle entries in the prepared integrand.
        """
    @property
    def variable_count(self) -> builtins.int:
        r"""
        Number of requested integration variables.
        """
    @property
    def indeterminate_count(self) -> builtins.int:
        r"""
        Number of exact Symbolica indeterminates in the prepared context.
        """
    @property
    def options(self) -> IntegrationOptions:
        r"""
        Independent copy of the options captured during preparation.
        """
    def integrate(self, options: typing.Optional[IntegrationOptions] = None) -> Expression:
        r"""
        Integrate and return a native Symbolica expression.
        """
    def integrate_detailed(self, options: typing.Optional[IntegrationOptions] = None) -> IntegrationResult:
        r"""
        Integrate and retain metadata about the collected exact result.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of prepared shuffle entries.
        """
    def __copy__(self) -> PreparedIntegral: ...
    def __deepcopy__(self, _memo: typing.Any) -> PreparedIntegral: ...
    def __repr__(self) -> builtins.str: ...

def integrate(expression: Expression, variables: typing.Sequence[Expression], options: typing.Optional[IntegrationOptions] = None) -> Expression:
    r"""
    Integrate a Symbolica expression over `[0, infinity)` in variable order.

    Parameters
    ----------
    expression:
        A native `symbolica.Expression` from the shipped Symbolica kernel.
        It is never converted to text.
    variables:
        Plain Symbolica symbols in integration order.
    options:
        Optional `IntegrationOptions`.

    Returns
    -------
    symbolica.Expression
        The normalized exact result.
    """

def integrate_detailed(expression: Expression, variables: typing.Sequence[Expression], options: typing.Optional[IntegrationOptions] = None) -> IntegrationResult:
    r"""
    Integrate and return an inspectable exact result.

    Parameters
    ----------
    expression:
        A native `symbolica.Expression` from the shipped Symbolica kernel.
    variables:
        Plain shipped Symbolica symbols in integration order.
    options:
        Optional `IntegrationOptions`.

    Returns
    -------
    IntegrationResult
        The returned
    `IntegrationResult` retains variables, indeterminates, algebraic-letter
    metadata, and the collected term count in addition to its expression.
    """

def integrate_detailed_over(expression: Expression, variables: typing.Sequence[Expression], intervals: typing.Sequence[tuple[Expression, Expression]], options: typing.Optional[IntegrationOptions] = None) -> IntegrationResult:
    r"""
    Integrate over arbitrary directed intervals and retain exact metadata.

    `intervals` contains one `(from, to)` pair per integration variable and
    accepts native real directed infinities through `Symbol.INFINITY`.
    """

def integrate_over(expression: Expression, variables: typing.Sequence[Expression], intervals: typing.Sequence[tuple[Expression, Expression]], options: typing.Optional[IntegrationOptions] = None) -> Expression:
    r"""
    Integrate over arbitrary directed intervals in variable order.

    Parameters
    ----------
    expression:
        A native `symbolica.Expression` from the shipped Symbolica kernel.
    variables:
        Plain Symbolica symbols in integration order.
    intervals:
        One `(from, to)` pair of native expressions per variable. Use
        `symbolica.Symbol.INFINITY` (or its negation) for directed infinity.
    options:
        Optional `IntegrationOptions`.

    Returns
    -------
    symbolica.Expression
        The normalized exact result.
    """

def mzv_symbol() -> Expression:
    r"""
    Return the registered multiple-zeta-value function symbol.

    Call the returned Symbolica expression with indices, e.g. `mzv_symbol()(3)`.
    This is the same head used in exact integration results. It is a formal
    symbol; for a depth-one numerical reference use Symbolica's built-in
    `E("3").zeta().evaluate({}, decimal_digit_precision=40)`.
    """

def prepare(expression: Expression, variables: typing.Sequence[Expression], options: typing.Optional[IntegrationOptions] = None) -> PreparedIntegral:
    r"""
    Lower a Symbolica expression once for repeated integrations or option sweeps.

    The returned immutable `PreparedIntegral` owns the lowered input and an
    independent copy of `options`. Mathematical input remains a native
    Symbolica expression throughout preparation.

    Parameters
    ----------
    expression:
        A native `symbolica.Expression` from the shipped Symbolica kernel.
    variables:
        Plain shipped Symbolica symbols in integration order.
    options:
        Options captured as the prepared object's default integration options.

    Returns
    -------
    PreparedIntegral
        Reusable immutable lowered input.
    """


class IntegrationError(Exception):
    """Base class for errors raised by Hyperbolica."""


class InputError(IntegrationError):
    """Invalid expression, integration-variable schedule, or options."""


class DuplicateVariableError(InputError):
    variable: str


class AlgebraError(IntegrationError):
    """Failure of an exact algebra operation."""


class DivergentIntegralError(IntegrationError):
    boundary: str
    variable: str
    log_power: int
    power: int


class UnsupportedFeatureError(IntegrationError):
    """The requested integration feature is unavailable for this input."""


class ContextError(AlgebraError):
    variable: str



__version__: str
__symbolica_version__: str
__api_version__: int
