"""Shared-kernel generation and lazy views on native and Pyodide hosts."""

import os
from typing import Any, final

class RustRedError(Exception): ...
class RustRedInputError(RustRedError): ...
class RustRedSchemaError(RustRedInputError): ...
class RustRedLimitError(RustRedInputError): ...
class RustRedLoweringError(RustRedInputError): ...
class RustRedDerivationError(RustRedError): ...
class RustRedExecutionError(RustRedError): ...
class RustRedLicenseError(RustRedExecutionError): ...
class RustRedSerializationError(RustRedError): ...
class RustRedOutputLimitError(RustRedSerializationError): ...
class RustRedInternalError(RustRedError): ...
class RustRedCoordinatorPoisonedError(RustRedInternalError): ...

@final
class CandidateBundleResult:
    @property
    def schema(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def bundle(self) -> bytes: ...
    def to_toml(self) -> str: ...
    def artifact(self) -> CandidateArtifact: ...

@final
class CandidateGenerationRequest:
    def start(self, *, event_capacity: int = 256) -> CandidateGenerationSession: ...

@final
class CandidateGenerationSession:
    def _repr_html_(self) -> str: ...
    @property
    def execution_mode(self) -> str: ...
    @property
    def done(self) -> bool: ...
    def cancel(self) -> None: ...
    def snapshot(self) -> dict[str, object]: ...
    def poll_events(self, max_events: int = 128, timeout: float = 0.0) -> dict[str, object]: ...
    def wait(self, timeout: float | None = None) -> bool: ...
    def result(self) -> CandidateBundleResult: ...

@final
class CandidateArtifact:
    def _repr_html_(self) -> str: ...
    @staticmethod
    def open(bundle: bytes, *, bundle_max_bytes: int | None = None,
             bundle_max_entries: int | None = None, bundle_max_coefficient_bytes: int | None = None,
             bundle_max_total_coefficient_bytes: int | None = None) -> CandidateArtifact: ...
    @staticmethod
    def open_file(path: str | os.PathLike[str], *, bundle_max_bytes: int | None = None,
                  bundle_max_entries: int | None = None, bundle_max_coefficient_bytes: int | None = None,
                  bundle_max_total_coefficient_bytes: int | None = None) -> CandidateArtifact: ...
    def metadata(self) -> dict[str, object]: ...
    def sectors(self, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def rules(self, sector: int, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def terminals(self, sector: int, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def rule(self, sector: int, ordinal: int, *, max_output_bytes: int = 1048576) -> dict[str, object]: ...
    def coefficient(self, id: int, *, max_output_bytes: int = 65536) -> dict[str, object]: ...

@final
class TerminalNormalization:
    """Exact family-local normalization, not closure or a minimal master basis.

    Coefficient IDs belong to this result, not to the input candidate artifact.
    Structural pages do not print coefficients; sidecar serialization is explicit.
    """
    def _repr_html_(self) -> str: ...
    def metadata(self) -> dict[str, object]: ...
    def terminals(self, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def relations(self, start: int = 0, limit: int = 50) -> dict[str, object]: ...
    def relation(self, ordinal: int, *, max_output_bytes: int = 1048576) -> dict[str, object]: ...
    def coefficient(self, id: int, *, max_output_bytes: int = 65536) -> dict[str, object]: ...
    def sidecar(self) -> bytes: ...

def candidate_generation_request(source: str, **options: object) -> CandidateGenerationRequest: ...
def start_family_candidates(source: str, *, event_capacity: int = 256, **options: object) -> CandidateGenerationSession: ...
def execution_capabilities() -> dict[str, object]:
    """Describe worker limits, background sessions, live events and cancellation.

    Pyodide executes synchronously with one worker and returns a completed
    session. Its buffered events describe completed work, not live progress.
    """
    ...

# Match the runtime namespace's forwarding of other embedded native APIs.
def __getattr__(name: str) -> Any: ...
