# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from symbolica.community.hepkit import FeynmanDiagram, Kinematics
from symbolica.core import Expression

@typing.final
class Chart:
    r"""
    Original chart ordinals and their retained native representative/kernel association.
    """
    @property
    def source_index(self) -> builtins.int: ...
    @property
    def representative(self) -> builtins.int: ...
    @property
    def representative_permutation(self) -> builtins.list[builtins.int]:
        r"""
        Permutes this chart's target coordinates into its representative's coordinates.
        """
    @property
    def kernel_sector(self) -> typing.Optional[builtins.int]:
        r"""
        None means no numerical kernel at the requested orders: exact, cancelled,
        or truncated. No separate per-chart exact coefficients are retained.
        """
    @property
    def coordinates(self) -> CoordinateMap: ...
    @property
    def geometry(self) -> SectorMap: ...

@typing.final
class CoefficientExpansionSnapshot:
    r"""
    Native per-representative coefficient work for the current or last attempt.
    """
    @property
    def sector(self) -> builtins.int:
        r"""
        Zero-based representative being processed or most recently completed.
        """
    @property
    def requested_method(self) -> builtins.str: ...
    @property
    def effective_method(self) -> builtins.str:
        r"""
        Physical also identifies an exact unregulated-endpoint fallback.
        """
    @property
    def stage(self) -> builtins.str: ...
    @property
    def attempt(self) -> builtins.int:
        r"""
        One-based native attempt; zero means admission or exact physical fallback.
        """
    @property
    def relative_width(self) -> builtins.int:
        r"""
        Native relative width; zero has the same pre-attempt/fallback meaning.
        This is not an absolute Laurent cutoff.
        """
    @property
    def formal_pieces(self) -> builtins.int:
        r"""
        Named-composition pieces in this attempt; zero for physical fallback.
        """
    @property
    def requests(self) -> CoefficientRequestCounts: ...

@typing.final
class CoefficientRequestCounts:
    r"""
    Native representation counts, reset at each coefficient-series attempt.
    """
    @property
    def source_bodies(self) -> builtins.int: ...
    @property
    def unique_requests(self) -> builtins.int: ...
    @property
    def cached_partials(self) -> builtins.int: ...
    @property
    def aliases(self) -> builtins.int: ...
    @property
    def interleaved_requests(self) -> builtins.int: ...
    @property
    def fallback_requests(self) -> builtins.int: ...

@typing.final
class CompactCoefficient:
    r"""
    A retained Symbolica alias root and definitions, without restoring a full expression.
    """
    @property
    def order(self) -> builtins.int:
        r"""
        Signed epsilon order of this possibly complex generated coefficient.
        Compiled kernels may split it into separate real/imaginary components.
        """
    @property
    def root(self) -> Expression: ...
    @property
    def alias_count(self) -> builtins.int:
        r"""
        Stored definitions for this coefficient; definitions may be shared with others.
        """
    @property
    def aliases(self) -> builtins.list[tuple[Expression, Expression]]:
        r"""
        Alias/definition pairs in native Atom order. Definitions may reference aliases.
        Read only for selected detail; this does not inline or expand any expression.
        """

@typing.final
class CoordinateMap:
    r"""
    Native density pullback before endpoint subtraction, including its positive measure.
    """
    @property
    def source_parameters(self) -> builtins.list[Expression]: ...
    @property
    def target_parameters(self) -> builtins.list[Expression]: ...
    @property
    def images(self) -> builtins.list[Expression]: ...
    @property
    def measure_jacobian(self) -> Expression:
        r"""
        Positive real density factor, not an oriented/complex determinant.
        A projective map is gauge-fixed, not a normalized simplex parameterization.
        """
    @property
    def source_domain(self) -> builtins.str: ...
    @property
    def projective_fixed_parameter(self) -> typing.Optional[builtins.int]: ...

@typing.final
class DomainAssessment:
    r"""
    The original native domain admission and its retained factor certificates.
    """
    @property
    def domain(self) -> builtins.str: ...
    @property
    def branch_policy(self) -> builtins.str: ...
    @property
    def caller_asserted(self) -> builtins.bool: ...
    @property
    def relies_on_assertion(self) -> builtins.bool: ...
    @property
    def parameters(self) -> builtins.list[Expression]: ...
    @property
    def factors(self) -> builtins.list[FactorAssessment]: ...

@typing.final
class EvaluationDiagnostics:
    r"""
    Native caller-aggregated evaluation counters, including failed attempts.
    """
    @property
    def evaluations(self) -> builtins.int: ...
    @property
    def conditioning_checks(self) -> builtins.int: ...
    @property
    def rescues(self) -> builtins.int: ...
    @property
    def max_precision_bits(self) -> builtins.int: ...
    @property
    def failures(self) -> builtins.int: ...
    @property
    def weighted_checks(self) -> builtins.int: ...
    @property
    def additional_replays(self) -> builtins.int: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class FactorAssessment:
    @property
    def term_index(self) -> builtins.int: ...
    @property
    def factor_index(self) -> builtins.int: ...
    @property
    def polynomial(self) -> Expression: ...
    @property
    def exponent(self) -> Expression: ...
    @property
    def certificate(self) -> builtins.str: ...

@typing.final
class GeneratedIntegral:
    @property
    def sectors(self) -> builtins.list[GeneratedSector]:
        r"""
        Immutable native sector views; coefficients remain compact until requested.
        """
    @property
    def metadata(self) -> GenerationMetadata:
        r"""
        Retained native domain and chart metadata, without evaluating the integral.
        """
    @property
    def orders(self) -> builtins.list[builtins.int]: ...
    @property
    def sector_count(self) -> builtins.int: ...
    @property
    def exact_coefficients(self) -> builtins.list[Expression]: ...
    def snapshot(self) -> GenerationSnapshot: ...
    def compile(self, *, observer: typing.Optional[typing.Any] = None) -> Kernels:
        r"""
        Build the configured native O2 or portable interpreted evaluator.
        """

@typing.final
class GeneratedSector:
    r"""
    A numerical sector at its native kernel-association index, with shared ownership.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        Native numerical-sector index used by Chart.kernel_sector.
        """
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def parameters(self) -> builtins.list[Expression]: ...
    @property
    def coefficient_count(self) -> builtins.int: ...
    @property
    def alias_counts(self) -> builtins.list[builtins.int]:
        r"""
        Stored alias definitions per coefficient, not a unique count across coefficients.
        """
    @property
    def cancellation_degree(self) -> builtins.int: ...
    @property
    def conditioning_basis(self) -> builtins.str:
        r"""
        Provenance of conditioning profiles, not a floating-point error certificate.
        """
    @property
    def cancellation_terms(self) -> builtins.list[builtins.list[builtins.int]]: ...
    @property
    def map(self) -> SectorMap: ...
    @property
    def aliased_coefficients(self) -> builtins.list[CompactCoefficient]:
        r"""
        Native complex coefficient roots/definitions aligned with GeneratedIntegral.orders.
        This creates cheap views; no coefficients are materialized or expanded.
        """

@typing.final
class GenerationMetadata:
    r"""
    Retained domain and chart associations; no decomposition is repeated by inspection.
    """
    @property
    def domain(self) -> DomainAssessment: ...
    @property
    def charts(self) -> builtins.list[Chart]: ...

@typing.final
class GenerationSnapshot:
    r"""
    Generation progress copied from the native caller-owned observer.
    """
    @property
    def stage(self) -> builtins.str:
        r"""
        Stable snake_case name of the native generation stage.
        """
    @property
    def completed(self) -> builtins.int: ...
    @property
    def total(self) -> typing.Optional[builtins.int]: ...
    @property
    def sectors(self) -> builtins.int: ...
    @property
    def kernels(self) -> builtins.int: ...
    @property
    def elapsed_seconds(self) -> builtins.float: ...
    @property
    def timings(self) -> GenerationTimings: ...
    @property
    def coefficient_expansion(self) -> typing.Optional[CoefficientExpansionSnapshot]:
        r"""
        Current or last named-coefficient attempt; None for physical-only generation.
        """
    @property
    def detail(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class GenerationTimings:
    r"""
    Native observed generation wall times in seconds.

    The total ends after preparing kernels and metadata, before artifact writing.
    """
    @property
    def input_seconds(self) -> builtins.float: ...
    @property
    def parametrization_seconds(self) -> builtins.float: ...
    @property
    def domain_seconds(self) -> builtins.float: ...
    @property
    def geometry_seconds(self) -> builtins.float: ...
    @property
    def mapping_seconds(self) -> builtins.float: ...
    @property
    def symmetry_seconds(self) -> builtins.float: ...
    @property
    def subtraction_seconds(self) -> builtins.float: ...
    @property
    def laurent_seconds(self) -> builtins.float: ...
    @property
    def coefficient_expansion_seconds(self) -> builtins.float:
        r"""
        Entire named phase, including any exact physical fallback.
        """
    @property
    def compilation_seconds(self) -> builtins.float: ...
    @property
    def total_seconds(self) -> builtins.float: ...

@typing.final
class Integral:
    r"""
    Native diagram, assumptions and explicit normalized loop measure.
    """
    @property
    def regulator(self) -> Expression: ...
    @property
    def dimension(self) -> Expression: ...
    @property
    def powers(self) -> builtins.list[tuple[builtins.int, builtins.int]]: ...
    def generate(self, max_order: builtins.int = 0, *, coefficient_expansion: builtins.str = 'physical', observer: typing.Optional[typing.Any] = None) -> GeneratedIntegral:
        r"""
        Synchronous native generation. False from the observer cancels at a native event boundary.
        """
    def __new__(cls, diagram: FeynmanDiagram, kinematics: Kinematics, *, regulator: Expression, dimension: typing.Optional[Expression] = None, powers: typing.Optional[typing.Mapping[builtins.int, builtins.int]] = None, scalar_values: typing.Optional[dict] = None, auxiliary_momenta: typing.Optional[typing.Sequence[Expression]] = None, measure_multiplier: typing.Optional[Expression] = None) -> Integral:
        r"""
        Kinematics retains its symbolic tensor dimension; dimension defaults to 4-2*regulator.
        """

@typing.final
class IntegrationSnapshot:
    r"""
    Coverage and estimates from the native caller-driven integration session.
    """
    @property
    def method(self) -> builtins.str: ...
    @property
    def stage(self) -> builtins.str: ...
    @property
    def completed_points(self) -> builtins.int: ...
    @property
    def planned_points(self) -> builtins.int: ...
    @property
    def complete_sectors(self) -> builtins.int: ...
    @property
    def sectors(self) -> builtins.list[SectorSnapshot]: ...
    @property
    def uncertainty(self) -> builtins.str:
        r"""
        Native validity state; statistical_failure retains its reason in uncertainty_detail.
        """
    @property
    def uncertainty_detail(self) -> typing.Optional[builtins.str]:
        r"""
        Native failure explanation, when the uncertainty state is statistical_failure.
        """
    @property
    def estimate(self) -> typing.Optional[VectorEstimate]:
        r"""
        Native full Laurent vector, or None when no valid estimate is available.
        """
    @property
    def worker_seconds(self) -> builtins.float:
        r"""
        Sum of worker execution times; caller wall time is separate.
        """
    @property
    def stop_reason(self) -> typing.Optional[builtins.str]:
        r"""
        Native caller-supplied stopping reason, or None while none is recorded.
        """
    @property
    def stop_detail(self) -> typing.Optional[builtins.str]:
        r"""
        Native failure explanation, when stop_reason is numerical_failure.
        """
    @property
    def evaluation_diagnostics(self) -> typing.Optional[EvaluationDiagnostics]: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Kernels:
    r"""
    Compiled native evaluator owners. Each session owns one lazy execution context.
    """
    @property
    def content_id(self) -> builtins.str: ...
    @property
    def orders(self) -> builtins.list[builtins.int]: ...
    @property
    def components(self) -> builtins.list[builtins.str]: ...
    @property
    def sector_count(self) -> builtins.int: ...
    @property
    def exact_coefficients(self) -> builtins.list[builtins.float]: ...
    @property
    def backend(self) -> builtins.str: ...
    def to_bytes(self) -> bytes:
        r"""
        Persist the library's native portable program/metadata codec, excluding machine code.
        """
    @staticmethod
    def from_bytes(artifact: bytes) -> Kernels:
        r"""
        Validate native programs and construct evaluators for the current host backend.
        """
    def snapshot(self) -> GenerationSnapshot: ...
    def session(self, settings: typing.Optional[QmcSettings] = None) -> QmcSession: ...
    def restore(self, checkpoint: bytes) -> QmcSession:
        r"""
        Restore complete accepted packages and replay state against these exact kernels.
        """

@typing.final
class QmcSession:
    r"""
    Caller-owned bounded execution, with no background loop or worker pool.
    """
    @property
    def complete(self) -> builtins.bool: ...
    @property
    def settings(self) -> QmcSettings: ...
    def snapshot(self) -> IntegrationSnapshot: ...
    def step(self, max_packages: builtins.int = 1, *, observer: typing.Optional[typing.Any] = None) -> IntegrationSnapshot:
        r"""
        Execute at most max_packages, returning to the Python caller between steps.
        An observer receives immutable snapshots after accepted packages; False stops this call.
        """
    def checkpoint(self) -> bytes: ...

@typing.final
class QmcSettings:
    @property
    def points(self) -> builtins.int: ...
    @property
    def shifts(self) -> builtins.int: ...
    @property
    def seed(self) -> builtins.int: ...
    @property
    def package_points(self) -> builtins.int: ...
    @property
    def periodization(self) -> builtins.str: ...
    @property
    def rule(self) -> builtins.str: ...
    def __new__(cls, *, points: builtins.int = 4096, shifts: builtins.int = 64, seed: builtins.int = 0, package_points: builtins.int = 1024, periodization: builtins.str = 'korobov3', rule: builtins.str = 'kuo_33002') -> QmcSettings:
        r"""
        Democratic QMC uses the native Kuo rule and retains full shift covariance.
        """

@typing.final
class SectorMap:
    r"""
    The retained exact integer geometry, with native Numerica-to-Python integer transport.
    """
    @property
    def source_dimension(self) -> builtins.int: ...
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def fixed_parameter(self) -> typing.Optional[builtins.int]: ...
    @property
    def exponent_matrix(self) -> builtins.list[builtins.list[int]]: ...
    @property
    def determinant(self) -> int: ...
    @property
    def jacobian_powers(self) -> builtins.list[int]: ...
    @property
    def factor_valuations(self) -> builtins.list[builtins.list[int]]:
        r"""
        Indices follow deduplicated support order, not uniquely named U/F factors.
        """

@typing.final
class SectorSnapshot:
    r"""
    Native per-sector work and complete-replica coverage.
    """
    @property
    def id(self) -> builtins.int: ...
    @property
    def dimension(self) -> builtins.int: ...
    @property
    def completed_points(self) -> builtins.int: ...
    @property
    def planned_points(self) -> builtins.int: ...
    @property
    def complete_replicas(self) -> builtins.int: ...
    @property
    def planned_replicas(self) -> builtins.int: ...
    @property
    def worker_seconds(self) -> builtins.float: ...

@typing.final
class VectorEstimate:
    r"""
    Native joint Laurent estimate with signed orders and full covariance.

    Returned arrays are independent copies. The bridge does not reconstruct
    uncertainty or combine components, sectors, or orders.
    """
    @property
    def orders(self) -> builtins.list[builtins.int]:
        r"""
        Signed epsilon powers, in exactly the native output order.
        """
    @property
    def components(self) -> builtins.list[builtins.str]:
        r"""
        A real or imag label for each native output entry.
        """
    @property
    def mean(self) -> builtins.list[builtins.float]: ...
    @property
    def standard_error(self) -> builtins.list[builtins.float]: ...
    @property
    def covariance_of_mean(self) -> builtins.list[builtins.float]:
        r"""
        Full row-major covariance of the mean, including inter-order and
        real/imaginary correlations. Entry (i, j) is at i * len(orders) + j.
        """
    @property
    def production_complete(self) -> builtins.bool:
        r"""
        Only a complete production allocation can certify an accuracy stop.
        """
    def meets(self, *, absolute: builtins.float = 0.0, relative: builtins.float = 0.001) -> builtins.bool:
        r"""
        Delegate convergence to the native full-production and vector tolerance check.
        """

def with_diagram_expressions(diagram: FeynmanDiagram, *, numerator: typing.Optional[Expression] = None, projector: typing.Optional[Expression] = None, overall_factor: typing.Optional[Expression] = None) -> FeynmanDiagram:
    r"""
    Copy a complete native diagram, replacing only the supplied expressions.
    Native numerator validation and all graph/model ownership are preserved.
    """


class FastSecDecError(RuntimeError):
    stage: str

class CancelledError(FastSecDecError): ...
